

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "43", "62", "64", "83", "85"],
		"CDFG" : "dct",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "383", "EstimateLatencyMax" : "383",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "41", "Name" : "read_data_U0"}],
		"OutputProcess" : [
			{"ID" : "85", "Name" : "write_data_U0"}],
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "read_data_U0", "Port" : "input_r"}]},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "write_data_U0", "Port" : "output_r"}]},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_0"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_0"}]},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_1"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_1"}]},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_2"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_2"}]},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_3"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_3"}]},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_4"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_4"}]},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_5"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_5"}]},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_6"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_6"}]},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "Loop_Row_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_7"},
					{"ID" : "64", "SubInstance" : "Loop_Col_DCT_Loop_proc_U0", "Port" : "dct_1d_dct_coeff_table_7"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_outbuf_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_1_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_2_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_3_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_4_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_5_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_6_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_outbuf_7_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_1_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_2_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_3_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_4_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_5_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_6_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_inbuf_7_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_8_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_9_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_10_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_11_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_12_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_13_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_14_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_8_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_9_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_10_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_11_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_12_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_13_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_14_U", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_data_U0", "Parent" : "0", "Child" : ["42"],
		"CDFG" : "read_data",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buf_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "25"},
			{"Name" : "buf_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "26"},
			{"Name" : "buf_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "27"},
			{"Name" : "buf_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "28"},
			{"Name" : "buf_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "29"},
			{"Name" : "buf_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "30"},
			{"Name" : "buf_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "31"},
			{"Name" : "buf_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["43"], "DependentChan" : "32"}],
		"Loop" : [
			{"Name" : "RD_Loop_Row", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_data_U0.flow_control_loop_pipe_U", "Parent" : "41"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0", "Parent" : "0", "Child" : ["44"],
		"CDFG" : "Loop_Row_DCT_Loop_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "145", "EstimateLatencyMax" : "145",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buf_2d_in_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "25"},
			{"Name" : "buf_2d_in_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "26"},
			{"Name" : "buf_2d_in_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "27"},
			{"Name" : "buf_2d_in_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "28"},
			{"Name" : "buf_2d_in_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "29"},
			{"Name" : "buf_2d_in_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "30"},
			{"Name" : "buf_2d_in_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "31"},
			{"Name" : "buf_2d_in_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["41"], "DependentChan" : "32"},
			{"Name" : "row_outbuf_i_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "7",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "6",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "5",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "4",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "3",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "2",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "1",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "row_outbuf_i_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "8",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_4", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_5", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_6", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_7", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}],
		"Loop" : [
			{"Name" : "Row_DCT_Loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190", "Parent" : "43", "Child" : ["45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61"],
		"CDFG" : "dct_1d",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "15",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "src_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "dst", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "DCT_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_0_U", "Parent" : "44"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_1_U", "Parent" : "44"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_2_U", "Parent" : "44"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_3_U", "Parent" : "44"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_4_U", "Parent" : "44"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_5_U", "Parent" : "44"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_6_U", "Parent" : "44"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_7_U", "Parent" : "44"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_15s_29_1_1_U10", "Parent" : "44"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_15s_29_1_1_U11", "Parent" : "44"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_14ns_29_1_1_U12", "Parent" : "44"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_13ns_29_4_1_U13", "Parent" : "44"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U14", "Parent" : "44"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U15", "Parent" : "44"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U16", "Parent" : "44"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U17", "Parent" : "44"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Row_DCT_Loop_proc_U0.grp_dct_1d_fu_190.flow_control_loop_pipe_sequential_init_U", "Parent" : "44"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_Xpose_Row_Outer_Loop_proc_U0", "Parent" : "0", "Child" : ["63"],
		"CDFG" : "Loop_Xpose_Row_Outer_Loop_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_inbuf_i_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "24"},
			{"Name" : "col_inbuf_i_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "23"},
			{"Name" : "col_inbuf_i_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "22"},
			{"Name" : "col_inbuf_i_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "21"},
			{"Name" : "col_inbuf_i_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "20"},
			{"Name" : "col_inbuf_i_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "19"},
			{"Name" : "col_inbuf_i_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "18"},
			{"Name" : "col_inbuf_i_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "17"},
			{"Name" : "row_outbuf_i_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "1"},
			{"Name" : "row_outbuf_i_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "2"},
			{"Name" : "row_outbuf_i_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "3"},
			{"Name" : "row_outbuf_i_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "4"},
			{"Name" : "row_outbuf_i_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "5"},
			{"Name" : "row_outbuf_i_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "6"},
			{"Name" : "row_outbuf_i_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "7"},
			{"Name" : "row_outbuf_i_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["43"], "DependentChan" : "8"}],
		"Loop" : [
			{"Name" : "Xpose_Row_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_Xpose_Row_Outer_Loop_proc_U0.flow_control_loop_pipe_U", "Parent" : "62"},
	{"ID" : "64", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0", "Parent" : "0", "Child" : ["65"],
		"CDFG" : "Loop_Col_DCT_Loop_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "145", "EstimateLatencyMax" : "145",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_inbuf_i_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "17"},
			{"Name" : "col_inbuf_i_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "18"},
			{"Name" : "col_inbuf_i_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "19"},
			{"Name" : "col_inbuf_i_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "20"},
			{"Name" : "col_inbuf_i_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "21"},
			{"Name" : "col_inbuf_i_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "22"},
			{"Name" : "col_inbuf_i_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "23"},
			{"Name" : "col_inbuf_i_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["62"], "DependentChan" : "24"},
			{"Name" : "col_outbuf_i_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "15",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "14",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "13",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "12",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "11",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "10",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "9",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "col_outbuf_i_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["83"], "DependentChan" : "16",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dst", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_4", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_5", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_6", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_dct_1d_fu_190", "Port" : "dct_1d_dct_coeff_table_7", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}],
		"Loop" : [
			{"Name" : "Col_DCT_Loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190", "Parent" : "64", "Child" : ["66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82"],
		"CDFG" : "dct_1d",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "15",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "src_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "src_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "dst", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "DCT_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_0_U", "Parent" : "65"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_1_U", "Parent" : "65"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_2_U", "Parent" : "65"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_3_U", "Parent" : "65"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_4_U", "Parent" : "65"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_5_U", "Parent" : "65"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_6_U", "Parent" : "65"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.dct_1d_dct_coeff_table_7_U", "Parent" : "65"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_15s_29_1_1_U10", "Parent" : "65"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_15s_29_1_1_U11", "Parent" : "65"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mul_16s_14ns_29_1_1_U12", "Parent" : "65"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_13ns_29_4_1_U13", "Parent" : "65"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U14", "Parent" : "65"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U15", "Parent" : "65"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U16", "Parent" : "65"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.mac_muladd_16s_15s_29s_29_4_1_U17", "Parent" : "65"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_Col_DCT_Loop_proc_U0.grp_dct_1d_fu_190.flow_control_loop_pipe_sequential_init_U", "Parent" : "65"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_Xpose_Col_Outer_Loop_proc_U0", "Parent" : "0", "Child" : ["84"],
		"CDFG" : "Loop_Xpose_Col_Outer_Loop_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buf_2d_out_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "40"},
			{"Name" : "buf_2d_out_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "39"},
			{"Name" : "buf_2d_out_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "38"},
			{"Name" : "buf_2d_out_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "37"},
			{"Name" : "buf_2d_out_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "36"},
			{"Name" : "buf_2d_out_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "35"},
			{"Name" : "buf_2d_out_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "34"},
			{"Name" : "buf_2d_out_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["85"], "DependentChan" : "33"},
			{"Name" : "col_outbuf_i_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "9"},
			{"Name" : "col_outbuf_i_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "10"},
			{"Name" : "col_outbuf_i_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "11"},
			{"Name" : "col_outbuf_i_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "12"},
			{"Name" : "col_outbuf_i_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "13"},
			{"Name" : "col_outbuf_i_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "14"},
			{"Name" : "col_outbuf_i_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "15"},
			{"Name" : "col_outbuf_i_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "16"}],
		"Loop" : [
			{"Name" : "Xpose_Col_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_Xpose_Col_Outer_Loop_proc_U0.flow_control_loop_pipe_U", "Parent" : "83"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_data_U0", "Parent" : "0", "Child" : ["86"],
		"CDFG" : "write_data",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buf_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "33"},
			{"Name" : "buf_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "34"},
			{"Name" : "buf_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "35"},
			{"Name" : "buf_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "36"},
			{"Name" : "buf_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "37"},
			{"Name" : "buf_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "38"},
			{"Name" : "buf_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "39"},
			{"Name" : "buf_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["83"], "DependentChan" : "40"},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "WR_Loop_Row", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_data_U0.flow_control_loop_pipe_U", "Parent" : "85"}]}
