-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_yuv_scale is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    p_yuv_width_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    p_yuv_width_empty_n : IN STD_LOGIC;
    p_yuv_width_read : OUT STD_LOGIC;
    p_yuv_width_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_yuv_width_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_yuv_height_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    p_yuv_height_empty_n : IN STD_LOGIC;
    p_yuv_height_read : OUT STD_LOGIC;
    p_yuv_height_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_yuv_height_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_yuv_channels_ch1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch1_empty_n : IN STD_LOGIC;
    p_yuv_channels_ch1_read : OUT STD_LOGIC;
    p_yuv_channels_ch1_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
    p_yuv_channels_ch1_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
    p_yuv_channels_ch2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch2_empty_n : IN STD_LOGIC;
    p_yuv_channels_ch2_read : OUT STD_LOGIC;
    p_yuv_channels_ch2_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
    p_yuv_channels_ch2_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
    p_yuv_channels_ch3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch3_empty_n : IN STD_LOGIC;
    p_yuv_channels_ch3_read : OUT STD_LOGIC;
    p_yuv_channels_ch3_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
    p_yuv_channels_ch3_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
    p_scale_channels_ch1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch1_full_n : IN STD_LOGIC;
    p_scale_channels_ch1_write : OUT STD_LOGIC;
    p_scale_channels_ch1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_channels_ch1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_channels_ch2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch2_full_n : IN STD_LOGIC;
    p_scale_channels_ch2_write : OUT STD_LOGIC;
    p_scale_channels_ch2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_channels_ch2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_channels_ch3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch3_full_n : IN STD_LOGIC;
    p_scale_channels_ch3_write : OUT STD_LOGIC;
    p_scale_channels_ch3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_channels_ch3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    p_scale_width_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_scale_width_full_n : IN STD_LOGIC;
    p_scale_width_write : OUT STD_LOGIC;
    p_scale_width_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_scale_width_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_scale_height_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_scale_height_full_n : IN STD_LOGIC;
    p_scale_height_write : OUT STD_LOGIC;
    p_scale_height_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_scale_height_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Y_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    Y_scale_empty_n : IN STD_LOGIC;
    Y_scale_read : OUT STD_LOGIC;
    Y_scale_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Y_scale_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    U_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    U_scale_empty_n : IN STD_LOGIC;
    U_scale_read : OUT STD_LOGIC;
    U_scale_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    U_scale_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    V_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    V_scale_empty_n : IN STD_LOGIC;
    V_scale_read : OUT STD_LOGIC;
    V_scale_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    V_scale_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of yuv_filter_yuv_scale is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal p_yuv_width_blk_n : STD_LOGIC;
    signal p_yuv_height_blk_n : STD_LOGIC;
    signal p_scale_width_blk_n : STD_LOGIC;
    signal p_scale_height_blk_n : STD_LOGIC;
    signal Y_scale_blk_n : STD_LOGIC;
    signal U_scale_blk_n : STD_LOGIC;
    signal V_scale_blk_n : STD_LOGIC;
    signal V_scale_1_reg_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal U_scale_1_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal Y_scale_1_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal width_reg_195 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_reg_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal bound_fu_150_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_reg_205 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_idle : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_ready : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch1_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch2_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch3_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal bound_fu_150_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal bound_fu_150_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal bound_fu_150_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_150_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_yuv_channels_ch1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_yuv_channels_ch1_empty_n : IN STD_LOGIC;
        p_yuv_channels_ch1_read : OUT STD_LOGIC;
        p_yuv_channels_ch1_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
        p_yuv_channels_ch1_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
        p_yuv_channels_ch2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_yuv_channels_ch2_empty_n : IN STD_LOGIC;
        p_yuv_channels_ch2_read : OUT STD_LOGIC;
        p_yuv_channels_ch2_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
        p_yuv_channels_ch2_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
        p_yuv_channels_ch3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_yuv_channels_ch3_empty_n : IN STD_LOGIC;
        p_yuv_channels_ch3_read : OUT STD_LOGIC;
        p_yuv_channels_ch3_num_data_valid : IN STD_LOGIC_VECTOR (22 downto 0);
        p_yuv_channels_ch3_fifo_cap : IN STD_LOGIC_VECTOR (22 downto 0);
        p_scale_channels_ch1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_scale_channels_ch1_full_n : IN STD_LOGIC;
        p_scale_channels_ch1_write : OUT STD_LOGIC;
        p_scale_channels_ch1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        p_scale_channels_ch1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_scale_channels_ch2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_scale_channels_ch2_full_n : IN STD_LOGIC;
        p_scale_channels_ch2_write : OUT STD_LOGIC;
        p_scale_channels_ch2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        p_scale_channels_ch2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_scale_channels_ch3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_scale_channels_ch3_full_n : IN STD_LOGIC;
        p_scale_channels_ch3_write : OUT STD_LOGIC;
        p_scale_channels_ch3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        p_scale_channels_ch3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln174 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln175 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln176 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component yuv_filter_mul_16ns_16ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100 : component yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start,
        ap_done => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done,
        ap_idle => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_idle,
        ap_ready => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_ready,
        p_yuv_channels_ch1_dout => p_yuv_channels_ch1_dout,
        p_yuv_channels_ch1_empty_n => p_yuv_channels_ch1_empty_n,
        p_yuv_channels_ch1_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch1_read,
        p_yuv_channels_ch1_num_data_valid => ap_const_lv23_0,
        p_yuv_channels_ch1_fifo_cap => ap_const_lv23_0,
        p_yuv_channels_ch2_dout => p_yuv_channels_ch2_dout,
        p_yuv_channels_ch2_empty_n => p_yuv_channels_ch2_empty_n,
        p_yuv_channels_ch2_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch2_read,
        p_yuv_channels_ch2_num_data_valid => ap_const_lv23_0,
        p_yuv_channels_ch2_fifo_cap => ap_const_lv23_0,
        p_yuv_channels_ch3_dout => p_yuv_channels_ch3_dout,
        p_yuv_channels_ch3_empty_n => p_yuv_channels_ch3_empty_n,
        p_yuv_channels_ch3_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch3_read,
        p_yuv_channels_ch3_num_data_valid => ap_const_lv23_0,
        p_yuv_channels_ch3_fifo_cap => ap_const_lv23_0,
        p_scale_channels_ch1_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_din,
        p_scale_channels_ch1_full_n => p_scale_channels_ch1_full_n,
        p_scale_channels_ch1_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_write,
        p_scale_channels_ch1_num_data_valid => p_scale_channels_ch1_num_data_valid,
        p_scale_channels_ch1_fifo_cap => p_scale_channels_ch1_fifo_cap,
        p_scale_channels_ch2_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_din,
        p_scale_channels_ch2_full_n => p_scale_channels_ch2_full_n,
        p_scale_channels_ch2_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_write,
        p_scale_channels_ch2_num_data_valid => p_scale_channels_ch2_num_data_valid,
        p_scale_channels_ch2_fifo_cap => p_scale_channels_ch2_fifo_cap,
        p_scale_channels_ch3_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_din,
        p_scale_channels_ch3_full_n => p_scale_channels_ch3_full_n,
        p_scale_channels_ch3_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_write,
        p_scale_channels_ch3_num_data_valid => p_scale_channels_ch3_num_data_valid,
        p_scale_channels_ch3_fifo_cap => p_scale_channels_ch3_fifo_cap,
        bound => bound_reg_205,
        zext_ln174 => Y_scale_1_reg_190,
        zext_ln175 => U_scale_1_reg_185,
        zext_ln176 => V_scale_1_reg_180);

    mul_16ns_16ns_32_1_1_U50 : component yuv_filter_mul_16ns_16ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => bound_fu_150_p0,
        din1 => bound_fu_150_p1,
        dout => bound_fu_150_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                U_scale_1_reg_185 <= U_scale_dout;
                V_scale_1_reg_180 <= V_scale_dout;
                Y_scale_1_reg_190 <= Y_scale_dout;
                height_reg_200 <= p_yuv_height_dout;
                width_reg_195 <= p_yuv_width_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_205 <= bound_fu_150_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    U_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, U_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            U_scale_blk_n <= U_scale_empty_n;
        else 
            U_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    U_scale_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            U_scale_read <= ap_const_logic_1;
        else 
            U_scale_read <= ap_const_logic_0;
        end if; 
    end process;


    V_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, V_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            V_scale_blk_n <= V_scale_empty_n;
        else 
            V_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    V_scale_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            V_scale_read <= ap_const_logic_1;
        else 
            V_scale_read <= ap_const_logic_0;
        end if; 
    end process;


    Y_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Y_scale_blk_n <= Y_scale_empty_n;
        else 
            Y_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Y_scale_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Y_scale_read <= ap_const_logic_1;
        else 
            Y_scale_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done)
    begin
        if ((grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, p_yuv_width_empty_n, p_yuv_height_empty_n, p_scale_width_full_n, p_scale_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
                ap_block_state1 <= ((p_scale_height_full_n = ap_const_logic_0) or (p_scale_width_full_n = ap_const_logic_0) or (p_yuv_height_empty_n = ap_const_logic_0) or (p_yuv_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    bound_fu_150_p0 <= bound_fu_150_p00(16 - 1 downto 0);
    bound_fu_150_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_reg_195),32));
    bound_fu_150_p1 <= bound_fu_150_p10(16 - 1 downto 0);
    bound_fu_150_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_reg_200),32));
    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch1_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_din;
    p_scale_channels_ch1_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch1_write;
    p_scale_channels_ch2_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_din;
    p_scale_channels_ch2_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch2_write;
    p_scale_channels_ch3_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_din;
    p_scale_channels_ch3_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_scale_channels_ch3_write;

    p_scale_height_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_scale_height_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_scale_height_blk_n <= p_scale_height_full_n;
        else 
            p_scale_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_scale_height_din <= p_yuv_height_dout;

    p_scale_height_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            p_scale_height_write <= ap_const_logic_1;
        else 
            p_scale_height_write <= ap_const_logic_0;
        end if; 
    end process;


    p_scale_width_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_scale_width_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_scale_width_blk_n <= p_scale_width_full_n;
        else 
            p_scale_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_scale_width_din <= p_yuv_width_dout;

    p_scale_width_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            p_scale_width_write <= ap_const_logic_1;
        else 
            p_scale_width_write <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch1_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch1_read;
    p_yuv_channels_ch2_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch2_read;
    p_yuv_channels_ch3_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100_p_yuv_channels_ch3_read;

    p_yuv_height_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_yuv_height_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_yuv_height_blk_n <= p_yuv_height_empty_n;
        else 
            p_yuv_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_yuv_height_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            p_yuv_height_read <= ap_const_logic_1;
        else 
            p_yuv_height_read <= ap_const_logic_0;
        end if; 
    end process;


    p_yuv_width_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_yuv_width_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_yuv_width_blk_n <= p_yuv_width_empty_n;
        else 
            p_yuv_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_yuv_width_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            p_yuv_width_read <= ap_const_logic_1;
        else 
            p_yuv_width_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
