// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module yuv_filter_yuv_filter_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln31,
        height,
        out_channels_ch1_address0,
        out_channels_ch1_ce0,
        out_channels_ch1_we0,
        out_channels_ch1_d0,
        out_channels_ch2_address0,
        out_channels_ch2_ce0,
        out_channels_ch2_we0,
        out_channels_ch2_d0,
        out_channels_ch3_address0,
        out_channels_ch3_ce0,
        out_channels_ch3_we0,
        out_channels_ch3_d0,
        p_scale_channels_ch1_address0,
        p_scale_channels_ch1_ce0,
        p_scale_channels_ch1_q0,
        p_scale_channels_ch2_address0,
        p_scale_channels_ch2_ce0,
        p_scale_channels_ch2_q0,
        p_scale_channels_ch3_address0,
        p_scale_channels_ch3_ce0,
        p_scale_channels_ch3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mul_ln31;
input  [15:0] height;
output  [21:0] out_channels_ch1_address0;
output   out_channels_ch1_ce0;
output   out_channels_ch1_we0;
output  [7:0] out_channels_ch1_d0;
output  [21:0] out_channels_ch2_address0;
output   out_channels_ch2_ce0;
output   out_channels_ch2_we0;
output  [7:0] out_channels_ch2_d0;
output  [21:0] out_channels_ch3_address0;
output   out_channels_ch3_ce0;
output   out_channels_ch3_we0;
output  [7:0] out_channels_ch3_d0;
output  [21:0] p_scale_channels_ch1_address0;
output   p_scale_channels_ch1_ce0;
input  [7:0] p_scale_channels_ch1_q0;
output  [21:0] p_scale_channels_ch2_address0;
output   p_scale_channels_ch2_ce0;
input  [7:0] p_scale_channels_ch2_q0;
output  [21:0] p_scale_channels_ch3_address0;
output   p_scale_channels_ch3_ce0;
input  [7:0] p_scale_channels_ch3_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln118_fu_236_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [21:0] add_ln134_fu_320_p2;
reg   [21:0] add_ln134_reg_696;
wire   [63:0] zext_ln134_1_fu_342_p1;
reg   [63:0] zext_ln134_1_reg_701;
reg   [63:0] zext_ln134_1_reg_701_pp0_iter3_reg;
reg   [63:0] zext_ln134_1_reg_701_pp0_iter4_reg;
reg   [63:0] zext_ln134_1_reg_701_pp0_iter5_reg;
reg   [63:0] zext_ln134_1_reg_701_pp0_iter6_reg;
reg   [63:0] zext_ln134_1_reg_701_pp0_iter7_reg;
wire   [0:0] xor_ln129_fu_402_p2;
reg   [0:0] xor_ln129_reg_740;
reg   [0:0] xor_ln129_reg_740_pp0_iter6_reg;
wire   [6:0] trunc_ln129_fu_408_p1;
reg   [6:0] trunc_ln129_reg_746;
reg   [6:0] trunc_ln129_reg_746_pp0_iter6_reg;
wire  signed [17:0] grp_fu_628_p3;
reg  signed [17:0] add_ln131_reg_757;
wire  signed [17:0] grp_fu_647_p3;
wire    ap_block_pp0_stage0;
reg   [15:0] y_fu_116;
wire   [15:0] add_ln122_fu_326_p2;
wire    ap_loop_init;
reg   [15:0] x_fu_120;
wire   [15:0] select_ln118_fu_278_p3;
reg   [31:0] indvar_flatten13_fu_124;
wire   [31:0] add_ln118_1_fu_242_p2;
reg   [31:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    p_scale_channels_ch1_ce0_local;
reg    p_scale_channels_ch3_ce0_local;
reg    p_scale_channels_ch2_ce0_local;
reg    out_channels_ch1_we0_local;
wire   [7:0] R_fu_472_p3;
reg    out_channels_ch1_ce0_local;
reg    out_channels_ch3_we0_local;
wire   [7:0] B_fu_565_p3;
reg    out_channels_ch3_ce0_local;
reg    out_channels_ch2_we0_local;
wire   [7:0] G_fu_619_p3;
reg    out_channels_ch2_ce0_local;
wire   [0:0] icmp_ln122_fu_265_p2;
wire   [15:0] add_ln118_fu_259_p2;
wire   [11:0] trunc_ln134_fu_286_p1;
wire   [13:0] trunc_ln134_1_fu_298_p1;
wire   [21:0] p_shl2_fu_290_p3;
wire   [21:0] p_shl3_fu_302_p3;
wire   [15:0] select_ln120_fu_270_p3;
wire   [21:0] add_ln122_1_fu_310_p2;
wire   [21:0] zext_ln134_fu_316_p1;
wire   [8:0] zext_ln128_fu_346_p1;
wire  signed [8:0] C_fu_350_p2;
wire   [0:0] bit_sel4_fu_360_p3;
wire   [0:0] xor_ln130_fu_368_p2;
wire   [6:0] trunc_ln130_fu_374_p1;
wire  signed [7:0] E_fu_378_p3;
wire   [0:0] bit_sel7_fu_394_p3;
wire  signed [7:0] D_fu_412_p3;
wire  signed [17:0] grp_fu_636_p3;
wire   [1:0] tmp_fu_427_p4;
wire   [0:0] icmp_ln131_fu_436_p2;
wire   [0:0] tmp_1_fu_442_p3;
wire   [0:0] or_ln131_fu_466_p2;
wire   [7:0] select_ln131_fu_458_p3;
wire   [7:0] trunc_ln4_fu_449_p4;
wire   [16:0] tmp_4_fu_481_p4;
wire   [9:0] tmp_5_fu_493_p4;
wire  signed [18:0] sext_ln133_1_fu_489_p1;
wire  signed [18:0] sext_ln133_2_fu_501_p1;
wire   [18:0] add_ln133_1_fu_505_p2;
wire  signed [18:0] sext_ln131_4_fu_424_p1;
wire   [18:0] add_ln133_fu_511_p2;
wire   [2:0] tmp_6_fu_517_p4;
wire   [0:0] icmp_ln133_fu_527_p2;
wire   [0:0] tmp_7_fu_533_p3;
wire   [0:0] or_ln133_fu_559_p2;
wire   [7:0] select_ln133_fu_551_p3;
wire   [7:0] trunc_ln6_fu_541_p4;
wire  signed [17:0] grp_fu_655_p3;
wire   [1:0] tmp_2_fu_574_p4;
wire   [0:0] icmp_ln132_fu_583_p2;
wire   [0:0] tmp_3_fu_589_p3;
wire   [0:0] or_ln132_fu_613_p2;
wire   [7:0] select_ln132_fu_605_p3;
wire   [7:0] trunc_ln5_fu_596_p4;
wire   [8:0] grp_fu_628_p1;
wire   [7:0] grp_fu_628_p2;
wire   [8:0] grp_fu_636_p0;
wire  signed [8:0] grp_fu_647_p0;
wire  signed [7:0] grp_fu_655_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 y_fu_116 = 16'd0;
#0 x_fu_120 = 16'd0;
#0 indvar_flatten13_fu_124 = 32'd0;
#0 ap_done_reg = 1'b0;
end

yuv_filter_mac_muladd_9s_9ns_8ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9ns_8ns_18_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(C_fu_350_p2),
    .din1(grp_fu_628_p1),
    .din2(grp_fu_628_p2),
    .ce(1'b1),
    .dout(grp_fu_628_p3)
);

yuv_filter_mac_muladd_9ns_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9ns_8s_18s_18_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_636_p0),
    .din1(E_fu_378_p3),
    .din2(grp_fu_628_p3),
    .ce(1'b1),
    .dout(grp_fu_636_p3)
);

yuv_filter_mac_muladd_9s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_8s_18s_18_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_647_p0),
    .din1(E_fu_378_p3),
    .din2(grp_fu_628_p3),
    .ce(1'b1),
    .dout(grp_fu_647_p3)
);

yuv_filter_mac_muladd_8s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_18s_18_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(D_fu_412_p3),
    .din1(grp_fu_655_p1),
    .din2(grp_fu_647_p3),
    .ce(1'b1),
    .dout(grp_fu_655_p3)
);

yuv_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln118_fu_236_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_124 <= add_ln118_1_fu_242_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_124 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_120 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_fu_120 <= select_ln118_fu_278_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_116 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            y_fu_116 <= add_ln122_fu_326_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        add_ln131_reg_757 <= grp_fu_628_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln134_reg_696 <= add_ln134_fu_320_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        trunc_ln129_reg_746 <= trunc_ln129_fu_408_p1;
        trunc_ln129_reg_746_pp0_iter6_reg <= trunc_ln129_reg_746;
        xor_ln129_reg_740 <= xor_ln129_fu_402_p2;
        xor_ln129_reg_740_pp0_iter6_reg <= xor_ln129_reg_740;
        zext_ln134_1_reg_701[21 : 0] <= zext_ln134_1_fu_342_p1[21 : 0];
        zext_ln134_1_reg_701_pp0_iter3_reg[21 : 0] <= zext_ln134_1_reg_701[21 : 0];
        zext_ln134_1_reg_701_pp0_iter4_reg[21 : 0] <= zext_ln134_1_reg_701_pp0_iter3_reg[21 : 0];
        zext_ln134_1_reg_701_pp0_iter5_reg[21 : 0] <= zext_ln134_1_reg_701_pp0_iter4_reg[21 : 0];
        zext_ln134_1_reg_701_pp0_iter6_reg[21 : 0] <= zext_ln134_1_reg_701_pp0_iter5_reg[21 : 0];
        zext_ln134_1_reg_701_pp0_iter7_reg[21 : 0] <= zext_ln134_1_reg_701_pp0_iter6_reg[21 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_236_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 32'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_channels_ch1_ce0_local = 1'b1;
    end else begin
        out_channels_ch1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_channels_ch1_we0_local = 1'b1;
    end else begin
        out_channels_ch1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        out_channels_ch2_ce0_local = 1'b1;
    end else begin
        out_channels_ch2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        out_channels_ch2_we0_local = 1'b1;
    end else begin
        out_channels_ch2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_channels_ch3_ce0_local = 1'b1;
    end else begin
        out_channels_ch3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_channels_ch3_we0_local = 1'b1;
    end else begin
        out_channels_ch3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch1_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_scale_channels_ch2_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_scale_channels_ch3_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_565_p3 = ((or_ln133_fu_559_p2[0:0] == 1'b1) ? select_ln133_fu_551_p3 : trunc_ln6_fu_541_p4);

assign C_fu_350_p2 = ($signed(zext_ln128_fu_346_p1) + $signed(9'd496));

assign D_fu_412_p3 = {{xor_ln129_fu_402_p2}, {trunc_ln129_fu_408_p1}};

assign E_fu_378_p3 = {{xor_ln130_fu_368_p2}, {trunc_ln130_fu_374_p1}};

assign G_fu_619_p3 = ((or_ln132_fu_613_p2[0:0] == 1'b1) ? select_ln132_fu_605_p3 : trunc_ln5_fu_596_p4);

assign R_fu_472_p3 = ((or_ln131_fu_466_p2[0:0] == 1'b1) ? select_ln131_fu_458_p3 : trunc_ln4_fu_449_p4);

assign add_ln118_1_fu_242_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 32'd1);

assign add_ln118_fu_259_p2 = (x_fu_120 + 16'd1);

assign add_ln122_1_fu_310_p2 = (p_shl2_fu_290_p3 + p_shl3_fu_302_p3);

assign add_ln122_fu_326_p2 = (select_ln120_fu_270_p3 + 16'd1);

assign add_ln133_1_fu_505_p2 = ($signed(sext_ln133_1_fu_489_p1) + $signed(sext_ln133_2_fu_501_p1));

assign add_ln133_fu_511_p2 = ($signed(add_ln133_1_fu_505_p2) + $signed(sext_ln131_4_fu_424_p1));

assign add_ln134_fu_320_p2 = (add_ln122_1_fu_310_p2 + zext_ln134_fu_316_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel4_fu_360_p3 = p_scale_channels_ch3_q0[8'd7];

assign bit_sel7_fu_394_p3 = p_scale_channels_ch2_q0[8'd7];

assign grp_fu_628_p1 = 18'd298;

assign grp_fu_628_p2 = 18'd128;

assign grp_fu_636_p0 = 18'd409;

assign grp_fu_647_p0 = 17'd130864;

assign grp_fu_655_p1 = 16'd65436;

assign icmp_ln118_fu_236_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == mul_ln31) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_265_p2 = ((y_fu_116 == height) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_436_p2 = ((tmp_fu_427_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_583_p2 = ((tmp_2_fu_574_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_527_p2 = (($signed(tmp_6_fu_517_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign or_ln131_fu_466_p2 = (tmp_1_fu_442_p3 | icmp_ln131_fu_436_p2);

assign or_ln132_fu_613_p2 = (tmp_3_fu_589_p3 | icmp_ln132_fu_583_p2);

assign or_ln133_fu_559_p2 = (tmp_7_fu_533_p3 | icmp_ln133_fu_527_p2);

assign out_channels_ch1_address0 = zext_ln134_1_reg_701_pp0_iter6_reg;

assign out_channels_ch1_ce0 = out_channels_ch1_ce0_local;

assign out_channels_ch1_d0 = R_fu_472_p3;

assign out_channels_ch1_we0 = out_channels_ch1_we0_local;

assign out_channels_ch2_address0 = zext_ln134_1_reg_701_pp0_iter7_reg;

assign out_channels_ch2_ce0 = out_channels_ch2_ce0_local;

assign out_channels_ch2_d0 = G_fu_619_p3;

assign out_channels_ch2_we0 = out_channels_ch2_we0_local;

assign out_channels_ch3_address0 = zext_ln134_1_reg_701_pp0_iter6_reg;

assign out_channels_ch3_ce0 = out_channels_ch3_ce0_local;

assign out_channels_ch3_d0 = B_fu_565_p3;

assign out_channels_ch3_we0 = out_channels_ch3_we0_local;

assign p_scale_channels_ch1_address0 = zext_ln134_1_fu_342_p1;

assign p_scale_channels_ch1_ce0 = p_scale_channels_ch1_ce0_local;

assign p_scale_channels_ch2_address0 = zext_ln134_1_reg_701_pp0_iter3_reg;

assign p_scale_channels_ch2_ce0 = p_scale_channels_ch2_ce0_local;

assign p_scale_channels_ch3_address0 = zext_ln134_1_reg_701;

assign p_scale_channels_ch3_ce0 = p_scale_channels_ch3_ce0_local;

assign p_shl2_fu_290_p3 = {{trunc_ln134_fu_286_p1}, {10'd0}};

assign p_shl3_fu_302_p3 = {{trunc_ln134_1_fu_298_p1}, {8'd0}};

assign select_ln118_fu_278_p3 = ((icmp_ln122_fu_265_p2[0:0] == 1'b1) ? add_ln118_fu_259_p2 : x_fu_120);

assign select_ln120_fu_270_p3 = ((icmp_ln122_fu_265_p2[0:0] == 1'b1) ? 16'd0 : y_fu_116);

assign select_ln131_fu_458_p3 = ((icmp_ln131_fu_436_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln132_fu_605_p3 = ((icmp_ln132_fu_583_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln133_fu_551_p3 = ((icmp_ln133_fu_527_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln131_4_fu_424_p1 = add_ln131_reg_757;

assign sext_ln133_1_fu_489_p1 = $signed(tmp_4_fu_481_p4);

assign sext_ln133_2_fu_501_p1 = $signed(tmp_5_fu_493_p4);

assign tmp_1_fu_442_p3 = grp_fu_636_p3[32'd17];

assign tmp_2_fu_574_p4 = {{grp_fu_655_p3[17:16]}};

assign tmp_3_fu_589_p3 = grp_fu_655_p3[32'd17];

assign tmp_4_fu_481_p4 = {{{xor_ln129_reg_740_pp0_iter6_reg}, {trunc_ln129_reg_746_pp0_iter6_reg}}, {9'd0}};

assign tmp_5_fu_493_p4 = {{{xor_ln129_reg_740_pp0_iter6_reg}, {trunc_ln129_reg_746_pp0_iter6_reg}}, {2'd0}};

assign tmp_6_fu_517_p4 = {{add_ln133_fu_511_p2[18:16]}};

assign tmp_7_fu_533_p3 = add_ln133_fu_511_p2[32'd18];

assign tmp_fu_427_p4 = {{grp_fu_636_p3[17:16]}};

assign trunc_ln129_fu_408_p1 = p_scale_channels_ch2_q0[6:0];

assign trunc_ln130_fu_374_p1 = p_scale_channels_ch3_q0[6:0];

assign trunc_ln134_1_fu_298_p1 = select_ln118_fu_278_p3[13:0];

assign trunc_ln134_fu_286_p1 = select_ln118_fu_278_p3[11:0];

assign trunc_ln4_fu_449_p4 = {{grp_fu_636_p3[15:8]}};

assign trunc_ln5_fu_596_p4 = {{grp_fu_655_p3[15:8]}};

assign trunc_ln6_fu_541_p4 = {{add_ln133_fu_511_p2[15:8]}};

assign xor_ln129_fu_402_p2 = (bit_sel7_fu_394_p3 ^ 1'd1);

assign xor_ln130_fu_368_p2 = (bit_sel4_fu_360_p3 ^ 1'd1);

assign zext_ln128_fu_346_p1 = p_scale_channels_ch1_q0;

assign zext_ln134_1_fu_342_p1 = add_ln134_reg_696;

assign zext_ln134_fu_316_p1 = select_ln120_fu_270_p3;

always @ (posedge ap_clk) begin
    zext_ln134_1_reg_701[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln134_1_reg_701_pp0_iter3_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln134_1_reg_701_pp0_iter4_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln134_1_reg_701_pp0_iter5_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln134_1_reg_701_pp0_iter6_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln134_1_reg_701_pp0_iter7_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
end

endmodule //yuv_filter_yuv_filter_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y
