// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dct_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        col_inbuf_address0,
        col_inbuf_ce0,
        col_inbuf_q0,
        col_inbuf_1_address0,
        col_inbuf_1_ce0,
        col_inbuf_1_q0,
        col_inbuf_2_address0,
        col_inbuf_2_ce0,
        col_inbuf_2_q0,
        col_inbuf_3_address0,
        col_inbuf_3_ce0,
        col_inbuf_3_q0,
        col_inbuf_4_address0,
        col_inbuf_4_ce0,
        col_inbuf_4_q0,
        col_inbuf_5_address0,
        col_inbuf_5_ce0,
        col_inbuf_5_q0,
        col_inbuf_6_address0,
        col_inbuf_6_ce0,
        col_inbuf_6_q0,
        col_inbuf_7_address0,
        col_inbuf_7_ce0,
        col_inbuf_7_q0,
        col_outbuf_address0,
        col_outbuf_ce0,
        col_outbuf_we0,
        col_outbuf_d0,
        dct_1d_dct_coeff_table_0_address0,
        dct_1d_dct_coeff_table_0_ce0,
        dct_1d_dct_coeff_table_0_q0,
        dct_1d_dct_coeff_table_1_address0,
        dct_1d_dct_coeff_table_1_ce0,
        dct_1d_dct_coeff_table_1_q0,
        dct_1d_dct_coeff_table_2_address0,
        dct_1d_dct_coeff_table_2_ce0,
        dct_1d_dct_coeff_table_2_q0,
        dct_1d_dct_coeff_table_3_address0,
        dct_1d_dct_coeff_table_3_ce0,
        dct_1d_dct_coeff_table_3_q0,
        dct_1d_dct_coeff_table_4_address0,
        dct_1d_dct_coeff_table_4_ce0,
        dct_1d_dct_coeff_table_4_q0,
        dct_1d_dct_coeff_table_5_address0,
        dct_1d_dct_coeff_table_5_ce0,
        dct_1d_dct_coeff_table_5_q0,
        dct_1d_dct_coeff_table_6_address0,
        dct_1d_dct_coeff_table_6_ce0,
        dct_1d_dct_coeff_table_6_q0,
        dct_1d_dct_coeff_table_7_address0,
        dct_1d_dct_coeff_table_7_ce0,
        dct_1d_dct_coeff_table_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] col_inbuf_address0;
output   col_inbuf_ce0;
input  [15:0] col_inbuf_q0;
output  [2:0] col_inbuf_1_address0;
output   col_inbuf_1_ce0;
input  [15:0] col_inbuf_1_q0;
output  [2:0] col_inbuf_2_address0;
output   col_inbuf_2_ce0;
input  [15:0] col_inbuf_2_q0;
output  [2:0] col_inbuf_3_address0;
output   col_inbuf_3_ce0;
input  [15:0] col_inbuf_3_q0;
output  [2:0] col_inbuf_4_address0;
output   col_inbuf_4_ce0;
input  [15:0] col_inbuf_4_q0;
output  [2:0] col_inbuf_5_address0;
output   col_inbuf_5_ce0;
input  [15:0] col_inbuf_5_q0;
output  [2:0] col_inbuf_6_address0;
output   col_inbuf_6_ce0;
input  [15:0] col_inbuf_6_q0;
output  [2:0] col_inbuf_7_address0;
output   col_inbuf_7_ce0;
input  [15:0] col_inbuf_7_q0;
output  [5:0] col_outbuf_address0;
output   col_outbuf_ce0;
output   col_outbuf_we0;
output  [15:0] col_outbuf_d0;
output  [2:0] dct_1d_dct_coeff_table_0_address0;
output   dct_1d_dct_coeff_table_0_ce0;
input  [13:0] dct_1d_dct_coeff_table_0_q0;
output  [2:0] dct_1d_dct_coeff_table_1_address0;
output   dct_1d_dct_coeff_table_1_ce0;
input  [14:0] dct_1d_dct_coeff_table_1_q0;
output  [2:0] dct_1d_dct_coeff_table_2_address0;
output   dct_1d_dct_coeff_table_2_ce0;
input  [14:0] dct_1d_dct_coeff_table_2_q0;
output  [2:0] dct_1d_dct_coeff_table_3_address0;
output   dct_1d_dct_coeff_table_3_ce0;
input  [14:0] dct_1d_dct_coeff_table_3_q0;
output  [2:0] dct_1d_dct_coeff_table_4_address0;
output   dct_1d_dct_coeff_table_4_ce0;
input  [14:0] dct_1d_dct_coeff_table_4_q0;
output  [2:0] dct_1d_dct_coeff_table_5_address0;
output   dct_1d_dct_coeff_table_5_ce0;
input  [14:0] dct_1d_dct_coeff_table_5_q0;
output  [2:0] dct_1d_dct_coeff_table_6_address0;
output   dct_1d_dct_coeff_table_6_ce0;
input  [14:0] dct_1d_dct_coeff_table_6_q0;
output  [2:0] dct_1d_dct_coeff_table_7_address0;
output   dct_1d_dct_coeff_table_7_ce0;
input  [14:0] dct_1d_dct_coeff_table_7_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln69_fu_329_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln69_fu_379_p1;
reg   [63:0] zext_ln69_reg_599;
reg   [63:0] zext_ln69_reg_599_pp0_iter1_reg;
wire   [63:0] zext_ln39_fu_392_p1;
reg   [63:0] zext_ln39_reg_615;
wire   [5:0] add_ln45_fu_401_p2;
reg   [5:0] add_ln45_reg_626;
reg   [5:0] add_ln45_reg_626_pp0_iter1_reg;
reg   [5:0] add_ln45_reg_626_pp0_iter2_reg;
reg   [5:0] add_ln45_reg_626_pp0_iter3_reg;
reg   [5:0] add_ln45_reg_626_pp0_iter4_reg;
reg   [5:0] add_ln45_reg_626_pp0_iter5_reg;
reg   [13:0] coeff_reg_736;
reg  signed [14:0] coeff_9_reg_746;
reg  signed [14:0] coeff_11_reg_756;
wire   [28:0] mul_ln45_9_fu_489_p2;
reg  signed [28:0] mul_ln45_9_reg_771;
wire   [28:0] mul_ln45_10_fu_495_p2;
reg  signed [28:0] mul_ln45_10_reg_776;
wire   [28:0] mul_ln45_12_fu_501_p2;
reg  signed [28:0] mul_ln45_12_reg_781;
wire  signed [28:0] grp_fu_535_p3;
wire  signed [28:0] grp_fu_543_p3;
reg  signed [28:0] add_ln45_8_reg_791;
wire  signed [28:0] grp_fu_550_p3;
reg  signed [28:0] add_ln45_9_reg_796;
(* use_dsp = "no" *) wire   [28:0] add_ln45_14_fu_507_p2;
reg   [28:0] add_ln45_14_reg_801;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln45_3_fu_511_p1;
reg   [3:0] k_fu_78;
wire   [3:0] add_ln39_fu_407_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_k_load;
reg   [3:0] i_fu_82;
wire   [3:0] select_ln69_fu_367_p3;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [6:0] indvar_flatten20_fu_86;
wire   [6:0] add_ln69_1_fu_335_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten20_load;
reg    col_inbuf_7_ce0_local;
reg    dct_1d_dct_coeff_table_7_ce0_local;
reg    col_inbuf_1_ce0_local;
reg    col_inbuf_3_ce0_local;
reg    col_inbuf_5_ce0_local;
reg    col_inbuf_6_ce0_local;
reg    dct_1d_dct_coeff_table_0_ce0_local;
reg    dct_1d_dct_coeff_table_1_ce0_local;
reg    dct_1d_dct_coeff_table_2_ce0_local;
reg    dct_1d_dct_coeff_table_3_ce0_local;
reg    dct_1d_dct_coeff_table_4_ce0_local;
reg    dct_1d_dct_coeff_table_5_ce0_local;
reg    dct_1d_dct_coeff_table_6_ce0_local;
reg    col_inbuf_ce0_local;
reg    col_inbuf_2_ce0_local;
reg    col_inbuf_4_ce0_local;
reg    col_outbuf_we0_local;
reg    col_outbuf_ce0_local;
wire   [0:0] icmp_ln39_fu_353_p2;
wire   [3:0] add_ln69_fu_347_p2;
wire   [2:0] trunc_ln69_fu_375_p1;
wire   [3:0] select_ln54_fu_359_p3;
wire   [5:0] tmp_3_fu_384_p3;
wire   [5:0] zext_ln45_fu_397_p1;
wire   [13:0] mul_ln45_9_fu_489_p0;
wire  signed [28:0] grp_fu_565_p3;
wire  signed [28:0] grp_fu_557_p3;
(* use_dsp = "no" *) wire   [28:0] add_ln45_10_fu_515_p2;
wire   [28:0] add_ln45_15_fu_519_p2;
wire   [12:0] grp_fu_535_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [28:0] mul_ln45_9_fu_489_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 k_fu_78 = 4'd0;
#0 i_fu_82 = 4'd0;
#0 indvar_flatten20_fu_86 = 7'd0;
#0 ap_done_reg = 1'b0;
end

dct_mul_14ns_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_14ns_16s_29_1_1_U48(
    .din0(mul_ln45_9_fu_489_p0),
    .din1(col_inbuf_q0),
    .dout(mul_ln45_9_fu_489_p2)
);

dct_mul_15s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_15s_16s_29_1_1_U49(
    .din0(coeff_9_reg_746),
    .din1(col_inbuf_2_q0),
    .dout(mul_ln45_10_fu_495_p2)
);

dct_mul_15s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_15s_16s_29_1_1_U50(
    .din0(coeff_11_reg_756),
    .din1(col_inbuf_4_q0),
    .dout(mul_ln45_12_fu_501_p2)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_7_q0),
    .din1(dct_1d_dct_coeff_table_7_q0),
    .din2(grp_fu_535_p2),
    .ce(1'b1),
    .dout(grp_fu_535_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_1_q0),
    .din1(dct_1d_dct_coeff_table_1_q0),
    .din2(mul_ln45_9_reg_771),
    .ce(1'b1),
    .dout(grp_fu_543_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_3_q0),
    .din1(dct_1d_dct_coeff_table_3_q0),
    .din2(mul_ln45_10_reg_776),
    .ce(1'b1),
    .dout(grp_fu_550_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_5_q0),
    .din1(dct_1d_dct_coeff_table_5_q0),
    .din2(mul_ln45_12_reg_781),
    .ce(1'b1),
    .dout(grp_fu_557_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(col_inbuf_6_q0),
    .din1(dct_1d_dct_coeff_table_6_q0),
    .din2(grp_fu_535_p3),
    .ce(1'b1),
    .dout(grp_fu_565_p3)
);

dct_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_329_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_82 <= select_ln69_fu_367_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_329_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_86 <= add_ln69_1_fu_335_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_86 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_329_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_78 <= add_ln39_fu_407_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_78 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln45_14_reg_801 <= add_ln45_14_fu_507_p2;
        add_ln45_reg_626_pp0_iter2_reg <= add_ln45_reg_626_pp0_iter1_reg;
        add_ln45_reg_626_pp0_iter3_reg <= add_ln45_reg_626_pp0_iter2_reg;
        add_ln45_reg_626_pp0_iter4_reg <= add_ln45_reg_626_pp0_iter3_reg;
        add_ln45_reg_626_pp0_iter5_reg <= add_ln45_reg_626_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        coeff_11_reg_756 <= dct_1d_dct_coeff_table_4_q0;
        coeff_9_reg_746 <= dct_1d_dct_coeff_table_2_q0;
        coeff_reg_736 <= dct_1d_dct_coeff_table_0_q0;
        mul_ln45_10_reg_776 <= mul_ln45_10_fu_495_p2;
        mul_ln45_12_reg_781 <= mul_ln45_12_fu_501_p2;
        mul_ln45_9_reg_771 <= mul_ln45_9_fu_489_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        add_ln45_8_reg_791 <= grp_fu_543_p3;
        add_ln45_9_reg_796 <= grp_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln45_reg_626 <= add_ln45_fu_401_p2;
        add_ln45_reg_626_pp0_iter1_reg <= add_ln45_reg_626;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln39_reg_615[3 : 0] <= zext_ln39_fu_392_p1[3 : 0];
        zext_ln69_reg_599[3 : 0] <= zext_ln69_fu_379_p1[3 : 0];
        zext_ln69_reg_599_pp0_iter1_reg[3 : 0] <= zext_ln69_reg_599[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln69_fu_329_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_load = 4'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_1_ce0_local = 1'b1;
    end else begin
        col_inbuf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        col_inbuf_2_ce0_local = 1'b1;
    end else begin
        col_inbuf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_3_ce0_local = 1'b1;
    end else begin
        col_inbuf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        col_inbuf_4_ce0_local = 1'b1;
    end else begin
        col_inbuf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_5_ce0_local = 1'b1;
    end else begin
        col_inbuf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_6_ce0_local = 1'b1;
    end else begin
        col_inbuf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_inbuf_7_ce0_local = 1'b1;
    end else begin
        col_inbuf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        col_inbuf_ce0_local = 1'b1;
    end else begin
        col_inbuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        col_outbuf_ce0_local = 1'b1;
    end else begin
        col_outbuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        col_outbuf_we0_local = 1'b1;
    end else begin
        col_outbuf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_fu_407_p2 = (select_ln54_fu_359_p3 + 4'd1);

assign add_ln45_10_fu_515_p2 = ($signed(add_ln45_9_reg_796) + $signed(add_ln45_8_reg_791));

assign add_ln45_14_fu_507_p2 = ($signed(grp_fu_565_p3) + $signed(grp_fu_557_p3));

assign add_ln45_15_fu_519_p2 = (add_ln45_14_reg_801 + add_ln45_10_fu_515_p2);

assign add_ln45_fu_401_p2 = (tmp_3_fu_384_p3 + zext_ln45_fu_397_p1);

assign add_ln69_1_fu_335_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 7'd1);

assign add_ln69_fu_347_p2 = (ap_sig_allocacmp_i_load + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign col_inbuf_1_address0 = zext_ln69_reg_599;

assign col_inbuf_1_ce0 = col_inbuf_1_ce0_local;

assign col_inbuf_2_address0 = zext_ln69_reg_599_pp0_iter1_reg;

assign col_inbuf_2_ce0 = col_inbuf_2_ce0_local;

assign col_inbuf_3_address0 = zext_ln69_reg_599;

assign col_inbuf_3_ce0 = col_inbuf_3_ce0_local;

assign col_inbuf_4_address0 = zext_ln69_reg_599_pp0_iter1_reg;

assign col_inbuf_4_ce0 = col_inbuf_4_ce0_local;

assign col_inbuf_5_address0 = zext_ln69_reg_599;

assign col_inbuf_5_ce0 = col_inbuf_5_ce0_local;

assign col_inbuf_6_address0 = zext_ln69_reg_599;

assign col_inbuf_6_ce0 = col_inbuf_6_ce0_local;

assign col_inbuf_7_address0 = zext_ln69_fu_379_p1;

assign col_inbuf_7_ce0 = col_inbuf_7_ce0_local;

assign col_inbuf_address0 = zext_ln69_reg_599_pp0_iter1_reg;

assign col_inbuf_ce0 = col_inbuf_ce0_local;

assign col_outbuf_address0 = zext_ln45_3_fu_511_p1;

assign col_outbuf_ce0 = col_outbuf_ce0_local;

assign col_outbuf_d0 = {{add_ln45_15_fu_519_p2[28:13]}};

assign col_outbuf_we0 = col_outbuf_we0_local;

assign dct_1d_dct_coeff_table_0_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_0_ce0 = dct_1d_dct_coeff_table_0_ce0_local;

assign dct_1d_dct_coeff_table_1_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_1_ce0 = dct_1d_dct_coeff_table_1_ce0_local;

assign dct_1d_dct_coeff_table_2_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_2_ce0 = dct_1d_dct_coeff_table_2_ce0_local;

assign dct_1d_dct_coeff_table_3_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_3_ce0 = dct_1d_dct_coeff_table_3_ce0_local;

assign dct_1d_dct_coeff_table_4_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_4_ce0 = dct_1d_dct_coeff_table_4_ce0_local;

assign dct_1d_dct_coeff_table_5_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_5_ce0 = dct_1d_dct_coeff_table_5_ce0_local;

assign dct_1d_dct_coeff_table_6_address0 = zext_ln39_reg_615;

assign dct_1d_dct_coeff_table_6_ce0 = dct_1d_dct_coeff_table_6_ce0_local;

assign dct_1d_dct_coeff_table_7_address0 = zext_ln39_fu_392_p1;

assign dct_1d_dct_coeff_table_7_ce0 = dct_1d_dct_coeff_table_7_ce0_local;

assign grp_fu_535_p2 = 29'd4096;

assign icmp_ln39_fu_353_p2 = ((ap_sig_allocacmp_k_load == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_329_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln45_9_fu_489_p0 = mul_ln45_9_fu_489_p00;

assign mul_ln45_9_fu_489_p00 = coeff_reg_736;

assign select_ln54_fu_359_p3 = ((icmp_ln39_fu_353_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_k_load);

assign select_ln69_fu_367_p3 = ((icmp_ln39_fu_353_p2[0:0] == 1'b1) ? add_ln69_fu_347_p2 : ap_sig_allocacmp_i_load);

assign tmp_3_fu_384_p3 = {{trunc_ln69_fu_375_p1}, {3'd0}};

assign trunc_ln69_fu_375_p1 = select_ln69_fu_367_p3[2:0];

assign zext_ln39_fu_392_p1 = select_ln54_fu_359_p3;

assign zext_ln45_3_fu_511_p1 = add_ln45_reg_626_pp0_iter5_reg;

assign zext_ln45_fu_397_p1 = select_ln54_fu_359_p3;

assign zext_ln69_fu_379_p1 = select_ln69_fu_367_p3;

always @ (posedge ap_clk) begin
    zext_ln69_reg_599[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln69_reg_599_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln39_reg_615[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //dct_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop
