

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "19", "84"],
		"CDFG" : "dct",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "390", "EstimateLatencyMax" : "390",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "17", "Name" : "read_data_U0"}],
		"OutputProcess" : [
			{"ID" : "84", "Name" : "write_data_U0"}],
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "read_data_U0", "Port" : "input_r"}]},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "84", "SubInstance" : "write_data_U0", "Port" : "output_r"}]},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_0"}]},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_1"}]},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_2"}]},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_3"}]},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_4"}]},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_5"}]},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_6"}]},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_7"}]},
			{"Name" : "dct_1d_dct_coeff_table_03", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_03"}]},
			{"Name" : "dct_1d_dct_coeff_table_14", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_14"}]},
			{"Name" : "dct_1d_dct_coeff_table_25", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_25"}]},
			{"Name" : "dct_1d_dct_coeff_table_36", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_36"}]},
			{"Name" : "dct_1d_dct_coeff_table_47", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_47"}]},
			{"Name" : "dct_1d_dct_coeff_table_58", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_58"}]},
			{"Name" : "dct_1d_dct_coeff_table_69", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_69"}]},
			{"Name" : "dct_1d_dct_coeff_table_710", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "dct_2d_U0", "Port" : "dct_1d_dct_coeff_table_710"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_in_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_1_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_2_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_3_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_4_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_5_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_6_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_2d_out_7_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_data_U0", "Parent" : "0", "Child" : ["18"],
		"CDFG" : "read_data",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buf_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "1"},
			{"Name" : "buf_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "2"},
			{"Name" : "buf_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "3"},
			{"Name" : "buf_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "4"},
			{"Name" : "buf_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "5"},
			{"Name" : "buf_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "6"},
			{"Name" : "buf_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "7"},
			{"Name" : "buf_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "8"}],
		"Loop" : [
			{"Name" : "RD_Loop_Row", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_data_U0.flow_control_loop_pipe_U", "Parent" : "17"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0", "Parent" : "0", "Child" : ["20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "46", "64", "66"],
		"CDFG" : "dct_2d",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "320", "EstimateLatencyMax" : "320",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_block_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "1"},
			{"Name" : "in_block_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "2"},
			{"Name" : "in_block_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "3"},
			{"Name" : "in_block_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "4"},
			{"Name" : "in_block_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "5"},
			{"Name" : "in_block_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "6"},
			{"Name" : "in_block_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "7"},
			{"Name" : "in_block_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "8"},
			{"Name" : "out_block_0", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "9",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_0", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "10",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_1", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "11",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_2", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "12",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_3", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "13",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_4", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "14",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_5", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "15",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_6", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "out_block_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["84"], "DependentChan" : "16",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Port" : "out_block_7", "Inst_start_state" : "7", "Inst_end_state" : "10"}]},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_4", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_5", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_6", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_dct_1d_11_12_fu_432", "Port" : "dct_1d_dct_coeff_table_7", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dct_1d_dct_coeff_table_03", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_03", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_14", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_14", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_25", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_25", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_36", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_36", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_47", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_47", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_58", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_58", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_69", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_69", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "dct_1d_dct_coeff_table_710", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "66", "SubInstance" : "grp_dct_1d_6_7_fu_497", "Port" : "dct_1d_dct_coeff_table_710", "Inst_start_state" : "8", "Inst_end_state" : "9"}]}],
		"Loop" : [
			{"Name" : "Row_DCT_Loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "10", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "Col_DCT_Loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "10", "FirstState" : "ap_ST_fsm_state7", "LastState" : ["ap_ST_fsm_state9"], "QuitState" : ["ap_ST_fsm_state7"], "PreState" : ["ap_ST_fsm_state6"], "PostState" : ["ap_ST_fsm_state10"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_U", "Parent" : "19"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_1_U", "Parent" : "19"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_2_U", "Parent" : "19"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_3_U", "Parent" : "19"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_4_U", "Parent" : "19"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_5_U", "Parent" : "19"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_6_U", "Parent" : "19"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.row_outbuf_7_U", "Parent" : "19"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_U", "Parent" : "19"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_1_U", "Parent" : "19"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_2_U", "Parent" : "19"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_3_U", "Parent" : "19"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_4_U", "Parent" : "19"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_5_U", "Parent" : "19"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_6_U", "Parent" : "19"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_outbuf_7_U", "Parent" : "19"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_U", "Parent" : "19"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_1_U", "Parent" : "19"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_2_U", "Parent" : "19"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_3_U", "Parent" : "19"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_4_U", "Parent" : "19"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_5_U", "Parent" : "19"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_6_U", "Parent" : "19"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.col_inbuf_7_U", "Parent" : "19"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_fu_412", "Parent" : "19", "Child" : ["45"],
		"CDFG" : "dct_2d_Pipeline_Xpose_Row_Outer_Loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_inbuf_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_inbuf", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_outbuf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_outbuf_7", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "Xpose_Row_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_fu_412.flow_control_loop_pipe_sequential_init_U", "Parent" : "44"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432", "Parent" : "19", "Child" : ["47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63"],
		"CDFG" : "dct_1d_11_12",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "15",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read3", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read4", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read5", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read6", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read7", "Type" : "None", "Direction" : "I"},
			{"Name" : "dst", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "dct_1d_dct_coeff_table_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_7", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "DCT_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_0_U", "Parent" : "46"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_1_U", "Parent" : "46"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_2_U", "Parent" : "46"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_3_U", "Parent" : "46"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_4_U", "Parent" : "46"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_5_U", "Parent" : "46"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_6_U", "Parent" : "46"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.dct_1d_dct_coeff_table_7_U", "Parent" : "46"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mul_16s_15s_29_1_1_U10", "Parent" : "46"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mul_16s_15s_29_1_1_U11", "Parent" : "46"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mul_16s_14ns_29_1_1_U12", "Parent" : "46"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mac_muladd_16s_15s_13ns_29_4_1_U13", "Parent" : "46"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mac_muladd_16s_15s_29s_29_4_1_U14", "Parent" : "46"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mac_muladd_16s_15s_29s_29_4_1_U15", "Parent" : "46"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mac_muladd_16s_15s_29s_29_4_1_U16", "Parent" : "46"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.mac_muladd_16s_15s_29s_29_4_1_U17", "Parent" : "46"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_11_12_fu_432.flow_control_loop_pipe_sequential_init_U", "Parent" : "46"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469", "Parent" : "19", "Child" : ["65"],
		"CDFG" : "dct_2d_Pipeline_Xpose_Col_Outer_Loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_block_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_block_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_outbuf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_outbuf_7", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "Xpose_Col_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_fu_469.flow_control_loop_pipe_sequential_init_U", "Parent" : "64"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497", "Parent" : "19", "Child" : ["67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83"],
		"CDFG" : "dct_1d_6_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "15",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read3", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read4", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read5", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read6", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read7", "Type" : "None", "Direction" : "I"},
			{"Name" : "dst", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "dct_1d_dct_coeff_table_03", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_36", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_47", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_58", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_69", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dct_1d_dct_coeff_table_710", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "DCT_Outer_Loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_03_U", "Parent" : "66"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_14_U", "Parent" : "66"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_25_U", "Parent" : "66"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_36_U", "Parent" : "66"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_47_U", "Parent" : "66"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_58_U", "Parent" : "66"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_69_U", "Parent" : "66"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.dct_1d_dct_coeff_table_710_U", "Parent" : "66"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mul_16s_15s_29_1_1_U55", "Parent" : "66"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mul_16s_15s_29_1_1_U56", "Parent" : "66"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mul_16s_14ns_29_1_1_U57", "Parent" : "66"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mac_muladd_16s_15s_13ns_29_4_1_U58", "Parent" : "66"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mac_muladd_16s_15s_29s_29_4_1_U59", "Parent" : "66"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mac_muladd_16s_15s_29s_29_4_1_U60", "Parent" : "66"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mac_muladd_16s_15s_29s_29_4_1_U61", "Parent" : "66"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.mac_muladd_16s_15s_29s_29_4_1_U62", "Parent" : "66"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dct_2d_U0.grp_dct_1d_6_7_fu_497.flow_control_loop_pipe_sequential_init_U", "Parent" : "66"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_data_U0", "Parent" : "0", "Child" : ["85"],
		"CDFG" : "write_data",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buf_0", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "9"},
			{"Name" : "buf_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "10"},
			{"Name" : "buf_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "11"},
			{"Name" : "buf_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "12"},
			{"Name" : "buf_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "13"},
			{"Name" : "buf_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "14"},
			{"Name" : "buf_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "15"},
			{"Name" : "buf_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["19"], "DependentChan" : "16"},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "WR_Loop_Row", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_data_U0.flow_control_loop_pipe_U", "Parent" : "84"}]}
