[hls]
relative_roots=C:/Users/duong/Desktop/xup_high_level_synthesis_design_flow-main/source/lab2
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=yuv_filter/RGB2YUV_LOOP_Y 
syn.directive.pipeline=yuv_filter/YUV_SCALE_LOOP_Y 
syn.directive.pipeline=yuv_filter/YUV2RGB_LOOP_Y 


