// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct_dct,hls_ip_2025_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-fgg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.380000,HLS_SYN_LAT=383,HLS_SYN_TPT=146,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2890,HLS_SYN_LUT=1561,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module dct (
        ap_clk,
        ap_rst,
        input_r_address0,
        input_r_ce0,
        input_r_d0,
        input_r_q0,
        input_r_we0,
        input_r_address1,
        input_r_ce1,
        input_r_d1,
        input_r_q1,
        input_r_we1,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst;
output  [5:0] input_r_address0;
output   input_r_ce0;
output  [15:0] input_r_d0;
input  [15:0] input_r_q0;
output   input_r_we0;
output  [5:0] input_r_address1;
output   input_r_ce1;
output  [15:0] input_r_d1;
input  [15:0] input_r_q1;
output   input_r_we1;
output  [5:0] output_r_address0;
output   output_r_ce0;
output  [15:0] output_r_d0;
input  [15:0] output_r_q0;
output   output_r_we0;
output  [5:0] output_r_address1;
output   output_r_ce1;
output  [15:0] output_r_d1;
input  [15:0] output_r_q1;
output   output_r_we1;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire   [15:0] row_outbuf_i_q0;
wire   [15:0] row_outbuf_t_q0;
wire   [15:0] row_outbuf_1_i_q0;
wire   [15:0] row_outbuf_1_t_q0;
wire   [15:0] row_outbuf_2_i_q0;
wire   [15:0] row_outbuf_2_t_q0;
wire   [15:0] row_outbuf_3_i_q0;
wire   [15:0] row_outbuf_3_t_q0;
wire   [15:0] row_outbuf_4_i_q0;
wire   [15:0] row_outbuf_4_t_q0;
wire   [15:0] row_outbuf_5_i_q0;
wire   [15:0] row_outbuf_5_t_q0;
wire   [15:0] row_outbuf_6_i_q0;
wire   [15:0] row_outbuf_6_t_q0;
wire   [15:0] row_outbuf_7_i_q0;
wire   [15:0] row_outbuf_7_t_q0;
wire   [15:0] col_outbuf_i_q0;
wire   [15:0] col_outbuf_t_q0;
wire   [15:0] col_outbuf_1_i_q0;
wire   [15:0] col_outbuf_1_t_q0;
wire   [15:0] col_outbuf_2_i_q0;
wire   [15:0] col_outbuf_2_t_q0;
wire   [15:0] col_outbuf_3_i_q0;
wire   [15:0] col_outbuf_3_t_q0;
wire   [15:0] col_outbuf_4_i_q0;
wire   [15:0] col_outbuf_4_t_q0;
wire   [15:0] col_outbuf_5_i_q0;
wire   [15:0] col_outbuf_5_t_q0;
wire   [15:0] col_outbuf_6_i_q0;
wire   [15:0] col_outbuf_6_t_q0;
wire   [15:0] col_outbuf_7_i_q0;
wire   [15:0] col_outbuf_7_t_q0;
wire   [15:0] col_inbuf_i_q0;
wire   [15:0] col_inbuf_t_q0;
wire   [15:0] col_inbuf_1_i_q0;
wire   [15:0] col_inbuf_1_t_q0;
wire   [15:0] col_inbuf_2_i_q0;
wire   [15:0] col_inbuf_2_t_q0;
wire   [15:0] col_inbuf_3_i_q0;
wire   [15:0] col_inbuf_3_t_q0;
wire   [15:0] col_inbuf_4_i_q0;
wire   [15:0] col_inbuf_4_t_q0;
wire   [15:0] col_inbuf_5_i_q0;
wire   [15:0] col_inbuf_5_t_q0;
wire   [15:0] col_inbuf_6_i_q0;
wire   [15:0] col_inbuf_6_t_q0;
wire   [15:0] col_inbuf_7_i_q0;
wire   [15:0] col_inbuf_7_t_q0;
wire   [15:0] buf_2d_in_i_q0;
wire   [15:0] buf_2d_in_t_q0;
wire   [15:0] buf_2d_in_8_i_q0;
wire   [15:0] buf_2d_in_8_t_q0;
wire   [15:0] buf_2d_in_9_i_q0;
wire   [15:0] buf_2d_in_9_t_q0;
wire   [15:0] buf_2d_in_10_i_q0;
wire   [15:0] buf_2d_in_10_t_q0;
wire   [15:0] buf_2d_in_11_i_q0;
wire   [15:0] buf_2d_in_11_t_q0;
wire   [15:0] buf_2d_in_12_i_q0;
wire   [15:0] buf_2d_in_12_t_q0;
wire   [15:0] buf_2d_in_13_i_q0;
wire   [15:0] buf_2d_in_13_t_q0;
wire   [15:0] buf_2d_in_14_i_q0;
wire   [15:0] buf_2d_in_14_t_q0;
wire   [15:0] buf_2d_out_i_q0;
wire   [15:0] buf_2d_out_t_q0;
wire   [15:0] buf_2d_out_8_i_q0;
wire   [15:0] buf_2d_out_8_t_q0;
wire   [15:0] buf_2d_out_9_i_q0;
wire   [15:0] buf_2d_out_9_t_q0;
wire   [15:0] buf_2d_out_10_i_q0;
wire   [15:0] buf_2d_out_10_t_q0;
wire   [15:0] buf_2d_out_11_i_q0;
wire   [15:0] buf_2d_out_11_t_q0;
wire   [15:0] buf_2d_out_12_i_q0;
wire   [15:0] buf_2d_out_12_t_q0;
wire   [15:0] buf_2d_out_13_i_q0;
wire   [15:0] buf_2d_out_13_t_q0;
wire   [15:0] buf_2d_out_14_i_q0;
wire   [15:0] buf_2d_out_14_t_q0;
wire    read_data_U0_ap_start;
wire    read_data_U0_ap_done;
wire    read_data_U0_ap_continue;
wire    read_data_U0_ap_idle;
wire    read_data_U0_ap_ready;
wire   [5:0] read_data_U0_input_r_address0;
wire    read_data_U0_input_r_ce0;
wire   [5:0] read_data_U0_input_r_address1;
wire    read_data_U0_input_r_ce1;
wire   [2:0] read_data_U0_buf_0_address0;
wire    read_data_U0_buf_0_ce0;
wire    read_data_U0_buf_0_we0;
wire   [15:0] read_data_U0_buf_0_d0;
wire   [2:0] read_data_U0_buf_1_address0;
wire    read_data_U0_buf_1_ce0;
wire    read_data_U0_buf_1_we0;
wire   [15:0] read_data_U0_buf_1_d0;
wire   [2:0] read_data_U0_buf_2_address0;
wire    read_data_U0_buf_2_ce0;
wire    read_data_U0_buf_2_we0;
wire   [15:0] read_data_U0_buf_2_d0;
wire   [2:0] read_data_U0_buf_3_address0;
wire    read_data_U0_buf_3_ce0;
wire    read_data_U0_buf_3_we0;
wire   [15:0] read_data_U0_buf_3_d0;
wire   [2:0] read_data_U0_buf_4_address0;
wire    read_data_U0_buf_4_ce0;
wire    read_data_U0_buf_4_we0;
wire   [15:0] read_data_U0_buf_4_d0;
wire   [2:0] read_data_U0_buf_5_address0;
wire    read_data_U0_buf_5_ce0;
wire    read_data_U0_buf_5_we0;
wire   [15:0] read_data_U0_buf_5_d0;
wire   [2:0] read_data_U0_buf_6_address0;
wire    read_data_U0_buf_6_ce0;
wire    read_data_U0_buf_6_we0;
wire   [15:0] read_data_U0_buf_6_d0;
wire   [2:0] read_data_U0_buf_7_address0;
wire    read_data_U0_buf_7_ce0;
wire    read_data_U0_buf_7_we0;
wire   [15:0] read_data_U0_buf_7_d0;
wire    ap_channel_done_buf_2d_in_14;
wire    read_data_U0_buf_7_full_n;
reg    ap_sync_reg_channel_write_buf_2d_in_14;
wire    ap_sync_channel_write_buf_2d_in_14;
wire    Loop_Row_DCT_Loop_proc_U0_ap_start;
wire    Loop_Row_DCT_Loop_proc_U0_ap_done;
wire    Loop_Row_DCT_Loop_proc_U0_ap_continue;
wire    Loop_Row_DCT_Loop_proc_U0_ap_idle;
wire    Loop_Row_DCT_Loop_proc_U0_ap_ready;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_address0;
wire    Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_ce0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_d0;
wire   [2:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_address0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_ce0;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_we0;
wire   [15:0] Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_d0;
wire    ap_channel_done_row_outbuf_7;
wire    Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_full_n;
reg    ap_sync_reg_channel_write_row_outbuf_7;
wire    ap_sync_channel_write_row_outbuf_7;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_ce0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_we0;
wire   [15:0] Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_d0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_ce0;
wire   [2:0] Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_address0;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_ce0;
wire    ap_channel_done_col_inbuf;
wire    Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_full_n;
reg    ap_sync_reg_channel_write_col_inbuf;
wire    ap_sync_channel_write_col_inbuf;
wire    Loop_Col_DCT_Loop_proc_U0_ap_start;
wire    Loop_Col_DCT_Loop_proc_U0_ap_done;
wire    Loop_Col_DCT_Loop_proc_U0_ap_continue;
wire    Loop_Col_DCT_Loop_proc_U0_ap_idle;
wire    Loop_Col_DCT_Loop_proc_U0_ap_ready;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_ce0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_d0;
wire   [2:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_address0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_ce0;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_we0;
wire   [15:0] Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_d0;
wire    ap_channel_done_col_outbuf_7;
wire    Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_full_n;
reg    ap_sync_reg_channel_write_col_outbuf_7;
wire    ap_sync_channel_write_col_outbuf_7;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_ce0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_we0;
wire   [15:0] Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_d0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_ce0;
wire   [2:0] Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_address0;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_ce0;
wire    ap_channel_done_buf_2d_out;
wire    Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_full_n;
reg    ap_sync_reg_channel_write_buf_2d_out;
wire    ap_sync_channel_write_buf_2d_out;
wire    write_data_U0_ap_start;
wire    write_data_U0_ap_done;
wire    write_data_U0_ap_continue;
wire    write_data_U0_ap_idle;
wire    write_data_U0_ap_ready;
wire   [2:0] write_data_U0_buf_0_address0;
wire    write_data_U0_buf_0_ce0;
wire   [2:0] write_data_U0_buf_1_address0;
wire    write_data_U0_buf_1_ce0;
wire   [2:0] write_data_U0_buf_2_address0;
wire    write_data_U0_buf_2_ce0;
wire   [2:0] write_data_U0_buf_3_address0;
wire    write_data_U0_buf_3_ce0;
wire   [2:0] write_data_U0_buf_4_address0;
wire    write_data_U0_buf_4_ce0;
wire   [2:0] write_data_U0_buf_5_address0;
wire    write_data_U0_buf_5_ce0;
wire   [2:0] write_data_U0_buf_6_address0;
wire    write_data_U0_buf_6_ce0;
wire   [2:0] write_data_U0_buf_7_address0;
wire    write_data_U0_buf_7_ce0;
wire   [5:0] write_data_U0_output_r_address0;
wire    write_data_U0_output_r_ce0;
wire    write_data_U0_output_r_we0;
wire   [15:0] write_data_U0_output_r_d0;
wire   [5:0] write_data_U0_output_r_address1;
wire    write_data_U0_output_r_ce1;
wire    write_data_U0_output_r_we1;
wire   [15:0] write_data_U0_output_r_d1;
wire    buf_2d_in_i_full_n;
wire    buf_2d_in_t_empty_n;
wire    buf_2d_in_8_i_full_n;
wire    buf_2d_in_8_t_empty_n;
wire    buf_2d_in_9_i_full_n;
wire    buf_2d_in_9_t_empty_n;
wire    buf_2d_in_10_i_full_n;
wire    buf_2d_in_10_t_empty_n;
wire    buf_2d_in_11_i_full_n;
wire    buf_2d_in_11_t_empty_n;
wire    buf_2d_in_12_i_full_n;
wire    buf_2d_in_12_t_empty_n;
wire    buf_2d_in_13_i_full_n;
wire    buf_2d_in_13_t_empty_n;
wire    buf_2d_in_14_i_full_n;
wire    buf_2d_in_14_t_empty_n;
wire    row_outbuf_6_i_full_n;
wire    row_outbuf_6_t_empty_n;
wire    row_outbuf_5_i_full_n;
wire    row_outbuf_5_t_empty_n;
wire    row_outbuf_4_i_full_n;
wire    row_outbuf_4_t_empty_n;
wire    row_outbuf_3_i_full_n;
wire    row_outbuf_3_t_empty_n;
wire    row_outbuf_2_i_full_n;
wire    row_outbuf_2_t_empty_n;
wire    row_outbuf_1_i_full_n;
wire    row_outbuf_1_t_empty_n;
wire    row_outbuf_i_full_n;
wire    row_outbuf_t_empty_n;
wire    row_outbuf_7_i_full_n;
wire    row_outbuf_7_t_empty_n;
wire    col_inbuf_7_i_full_n;
wire    col_inbuf_7_t_empty_n;
wire    col_inbuf_6_i_full_n;
wire    col_inbuf_6_t_empty_n;
wire    col_inbuf_5_i_full_n;
wire    col_inbuf_5_t_empty_n;
wire    col_inbuf_4_i_full_n;
wire    col_inbuf_4_t_empty_n;
wire    col_inbuf_3_i_full_n;
wire    col_inbuf_3_t_empty_n;
wire    col_inbuf_2_i_full_n;
wire    col_inbuf_2_t_empty_n;
wire    col_inbuf_1_i_full_n;
wire    col_inbuf_1_t_empty_n;
wire    col_inbuf_i_full_n;
wire    col_inbuf_t_empty_n;
wire    col_outbuf_6_i_full_n;
wire    col_outbuf_6_t_empty_n;
wire    col_outbuf_5_i_full_n;
wire    col_outbuf_5_t_empty_n;
wire    col_outbuf_4_i_full_n;
wire    col_outbuf_4_t_empty_n;
wire    col_outbuf_3_i_full_n;
wire    col_outbuf_3_t_empty_n;
wire    col_outbuf_2_i_full_n;
wire    col_outbuf_2_t_empty_n;
wire    col_outbuf_1_i_full_n;
wire    col_outbuf_1_t_empty_n;
wire    col_outbuf_i_full_n;
wire    col_outbuf_t_empty_n;
wire    col_outbuf_7_i_full_n;
wire    col_outbuf_7_t_empty_n;
wire    buf_2d_out_14_i_full_n;
wire    buf_2d_out_14_t_empty_n;
wire    buf_2d_out_13_i_full_n;
wire    buf_2d_out_13_t_empty_n;
wire    buf_2d_out_12_i_full_n;
wire    buf_2d_out_12_t_empty_n;
wire    buf_2d_out_11_i_full_n;
wire    buf_2d_out_11_t_empty_n;
wire    buf_2d_out_10_i_full_n;
wire    buf_2d_out_10_t_empty_n;
wire    buf_2d_out_9_i_full_n;
wire    buf_2d_out_9_t_empty_n;
wire    buf_2d_out_8_i_full_n;
wire    buf_2d_out_8_t_empty_n;
wire    buf_2d_out_i_full_n;
wire    buf_2d_out_t_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_buf_2d_in_14 = 1'b0;
#0 ap_sync_reg_channel_write_row_outbuf_7 = 1'b0;
#0 ap_sync_reg_channel_write_col_inbuf = 1'b0;
#0 ap_sync_reg_channel_write_col_outbuf_7 = 1'b0;
#0 ap_sync_reg_channel_write_buf_2d_out = 1'b0;
end

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_d0),
    .i_q0(row_outbuf_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_d0),
    .i_q0(row_outbuf_1_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_1_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_1_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_d0),
    .i_q0(row_outbuf_2_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_2_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_2_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_d0),
    .i_q0(row_outbuf_3_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_3_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_3_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_3_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_d0),
    .i_q0(row_outbuf_4_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_4_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_4_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_4_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_d0),
    .i_q0(row_outbuf_5_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_5_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_5_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_5_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_d0),
    .i_q0(row_outbuf_6_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_6_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_6_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_6_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
row_outbuf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_address0),
    .i_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_ce0),
    .i_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_we0),
    .i_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_d0),
    .i_q0(row_outbuf_7_i_q0),
    .t_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_address0),
    .t_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(row_outbuf_7_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(row_outbuf_7_i_full_n),
    .i_write(ap_channel_done_row_outbuf_7),
    .t_empty_n(row_outbuf_7_t_empty_n),
    .t_read(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_d0),
    .i_q0(col_outbuf_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_d0),
    .i_q0(col_outbuf_1_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_1_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_1_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_d0),
    .i_q0(col_outbuf_2_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_2_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_2_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_d0),
    .i_q0(col_outbuf_3_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_3_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_3_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_3_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_d0),
    .i_q0(col_outbuf_4_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_4_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_4_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_4_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_d0),
    .i_q0(col_outbuf_5_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_5_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_5_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_5_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_d0),
    .i_q0(col_outbuf_6_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_6_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_6_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_6_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_outbuf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_address0),
    .i_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_ce0),
    .i_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_we0),
    .i_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_d0),
    .i_q0(col_outbuf_7_i_q0),
    .t_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_address0),
    .t_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_outbuf_7_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_outbuf_7_i_full_n),
    .i_write(ap_channel_done_col_outbuf_7),
    .t_empty_n(col_outbuf_7_t_empty_n),
    .t_read(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_d0),
    .i_q0(col_inbuf_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_d0),
    .i_q0(col_inbuf_1_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_1_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_1_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_d0),
    .i_q0(col_inbuf_2_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_2_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_2_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_d0),
    .i_q0(col_inbuf_3_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_3_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_3_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_3_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_d0),
    .i_q0(col_inbuf_4_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_4_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_4_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_4_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_d0),
    .i_q0(col_inbuf_5_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_5_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_5_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_5_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_d0),
    .i_q0(col_inbuf_6_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_6_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_6_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_6_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_address0),
    .i_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_ce0),
    .i_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_we0),
    .i_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_d0),
    .i_q0(col_inbuf_7_i_q0),
    .t_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_address0),
    .t_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(col_inbuf_7_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(col_inbuf_7_i_full_n),
    .i_write(ap_channel_done_col_inbuf),
    .t_empty_n(col_inbuf_7_t_empty_n),
    .t_read(Loop_Col_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_0_address0),
    .i_ce0(read_data_U0_buf_0_ce0),
    .i_we0(read_data_U0_buf_0_we0),
    .i_d0(read_data_U0_buf_0_d0),
    .i_q0(buf_2d_in_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_1_address0),
    .i_ce0(read_data_U0_buf_1_ce0),
    .i_we0(read_data_U0_buf_1_we0),
    .i_d0(read_data_U0_buf_1_d0),
    .i_q0(buf_2d_in_8_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_8_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_8_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_8_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_2_address0),
    .i_ce0(read_data_U0_buf_2_ce0),
    .i_we0(read_data_U0_buf_2_we0),
    .i_d0(read_data_U0_buf_2_d0),
    .i_q0(buf_2d_in_9_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_9_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_9_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_9_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_3_address0),
    .i_ce0(read_data_U0_buf_3_ce0),
    .i_we0(read_data_U0_buf_3_we0),
    .i_d0(read_data_U0_buf_3_d0),
    .i_q0(buf_2d_in_10_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_10_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_10_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_10_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_4_address0),
    .i_ce0(read_data_U0_buf_4_ce0),
    .i_we0(read_data_U0_buf_4_we0),
    .i_d0(read_data_U0_buf_4_d0),
    .i_q0(buf_2d_in_11_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_11_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_11_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_11_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_5_address0),
    .i_ce0(read_data_U0_buf_5_ce0),
    .i_we0(read_data_U0_buf_5_we0),
    .i_d0(read_data_U0_buf_5_d0),
    .i_q0(buf_2d_in_12_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_12_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_12_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_12_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_6_address0),
    .i_ce0(read_data_U0_buf_6_ce0),
    .i_we0(read_data_U0_buf_6_we0),
    .i_d0(read_data_U0_buf_6_d0),
    .i_q0(buf_2d_in_13_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_13_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_13_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_13_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(read_data_U0_buf_7_address0),
    .i_ce0(read_data_U0_buf_7_ce0),
    .i_we0(read_data_U0_buf_7_we0),
    .i_d0(read_data_U0_buf_7_d0),
    .i_q0(buf_2d_in_14_i_q0),
    .t_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_address0),
    .t_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_in_14_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_in_14_i_full_n),
    .i_write(ap_channel_done_buf_2d_in_14),
    .t_empty_n(buf_2d_in_14_t_empty_n),
    .t_read(Loop_Row_DCT_Loop_proc_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_d0),
    .i_q0(buf_2d_out_i_q0),
    .t_address0(write_data_U0_buf_0_address0),
    .t_ce0(write_data_U0_buf_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_d0),
    .i_q0(buf_2d_out_8_i_q0),
    .t_address0(write_data_U0_buf_1_address0),
    .t_ce0(write_data_U0_buf_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_8_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_8_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_8_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_d0),
    .i_q0(buf_2d_out_9_i_q0),
    .t_address0(write_data_U0_buf_2_address0),
    .t_ce0(write_data_U0_buf_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_9_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_9_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_9_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_d0),
    .i_q0(buf_2d_out_10_i_q0),
    .t_address0(write_data_U0_buf_3_address0),
    .t_ce0(write_data_U0_buf_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_10_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_10_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_10_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_d0),
    .i_q0(buf_2d_out_11_i_q0),
    .t_address0(write_data_U0_buf_4_address0),
    .t_ce0(write_data_U0_buf_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_11_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_11_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_11_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_d0),
    .i_q0(buf_2d_out_12_i_q0),
    .t_address0(write_data_U0_buf_5_address0),
    .t_ce0(write_data_U0_buf_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_12_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_12_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_12_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_d0),
    .i_q0(buf_2d_out_13_i_q0),
    .t_address0(write_data_U0_buf_6_address0),
    .t_ce0(write_data_U0_buf_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_13_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_13_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_13_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_out_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_address0),
    .i_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_ce0),
    .i_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_we0),
    .i_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_d0),
    .i_q0(buf_2d_out_14_i_q0),
    .t_address0(write_data_U0_buf_7_address0),
    .t_ce0(write_data_U0_buf_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(buf_2d_out_14_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buf_2d_out_14_i_full_n),
    .i_write(ap_channel_done_buf_2d_out),
    .t_empty_n(buf_2d_out_14_t_empty_n),
    .t_read(write_data_U0_ap_ready)
);

dct_read_data read_data_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_data_U0_ap_start),
    .ap_done(read_data_U0_ap_done),
    .ap_continue(read_data_U0_ap_continue),
    .ap_idle(read_data_U0_ap_idle),
    .ap_ready(read_data_U0_ap_ready),
    .input_r_address0(read_data_U0_input_r_address0),
    .input_r_ce0(read_data_U0_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(read_data_U0_input_r_address1),
    .input_r_ce1(read_data_U0_input_r_ce1),
    .input_r_q1(input_r_q1),
    .buf_0_address0(read_data_U0_buf_0_address0),
    .buf_0_ce0(read_data_U0_buf_0_ce0),
    .buf_0_we0(read_data_U0_buf_0_we0),
    .buf_0_d0(read_data_U0_buf_0_d0),
    .buf_1_address0(read_data_U0_buf_1_address0),
    .buf_1_ce0(read_data_U0_buf_1_ce0),
    .buf_1_we0(read_data_U0_buf_1_we0),
    .buf_1_d0(read_data_U0_buf_1_d0),
    .buf_2_address0(read_data_U0_buf_2_address0),
    .buf_2_ce0(read_data_U0_buf_2_ce0),
    .buf_2_we0(read_data_U0_buf_2_we0),
    .buf_2_d0(read_data_U0_buf_2_d0),
    .buf_3_address0(read_data_U0_buf_3_address0),
    .buf_3_ce0(read_data_U0_buf_3_ce0),
    .buf_3_we0(read_data_U0_buf_3_we0),
    .buf_3_d0(read_data_U0_buf_3_d0),
    .buf_4_address0(read_data_U0_buf_4_address0),
    .buf_4_ce0(read_data_U0_buf_4_ce0),
    .buf_4_we0(read_data_U0_buf_4_we0),
    .buf_4_d0(read_data_U0_buf_4_d0),
    .buf_5_address0(read_data_U0_buf_5_address0),
    .buf_5_ce0(read_data_U0_buf_5_ce0),
    .buf_5_we0(read_data_U0_buf_5_we0),
    .buf_5_d0(read_data_U0_buf_5_d0),
    .buf_6_address0(read_data_U0_buf_6_address0),
    .buf_6_ce0(read_data_U0_buf_6_ce0),
    .buf_6_we0(read_data_U0_buf_6_we0),
    .buf_6_d0(read_data_U0_buf_6_d0),
    .buf_7_address0(read_data_U0_buf_7_address0),
    .buf_7_ce0(read_data_U0_buf_7_ce0),
    .buf_7_we0(read_data_U0_buf_7_we0),
    .buf_7_d0(read_data_U0_buf_7_d0)
);

dct_Loop_Row_DCT_Loop_proc Loop_Row_DCT_Loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Row_DCT_Loop_proc_U0_ap_start),
    .ap_done(Loop_Row_DCT_Loop_proc_U0_ap_done),
    .ap_continue(Loop_Row_DCT_Loop_proc_U0_ap_continue),
    .ap_idle(Loop_Row_DCT_Loop_proc_U0_ap_idle),
    .ap_ready(Loop_Row_DCT_Loop_proc_U0_ap_ready),
    .buf_2d_in_0_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0),
    .buf_2d_in_0_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0),
    .buf_2d_in_0_q0(buf_2d_in_t_q0),
    .buf_2d_in_1_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0),
    .buf_2d_in_1_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0),
    .buf_2d_in_1_q0(buf_2d_in_8_t_q0),
    .buf_2d_in_2_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0),
    .buf_2d_in_2_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0),
    .buf_2d_in_2_q0(buf_2d_in_9_t_q0),
    .buf_2d_in_3_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0),
    .buf_2d_in_3_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0),
    .buf_2d_in_3_q0(buf_2d_in_10_t_q0),
    .buf_2d_in_4_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_address0),
    .buf_2d_in_4_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_4_ce0),
    .buf_2d_in_4_q0(buf_2d_in_11_t_q0),
    .buf_2d_in_5_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_address0),
    .buf_2d_in_5_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_5_ce0),
    .buf_2d_in_5_q0(buf_2d_in_12_t_q0),
    .buf_2d_in_6_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_address0),
    .buf_2d_in_6_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_6_ce0),
    .buf_2d_in_6_q0(buf_2d_in_13_t_q0),
    .buf_2d_in_7_address0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_address0),
    .buf_2d_in_7_ce0(Loop_Row_DCT_Loop_proc_U0_buf_2d_in_7_ce0),
    .buf_2d_in_7_q0(buf_2d_in_14_t_q0),
    .row_outbuf_i_6_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_address0),
    .row_outbuf_i_6_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_ce0),
    .row_outbuf_i_6_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_we0),
    .row_outbuf_i_6_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_6_d0),
    .row_outbuf_i_5_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_address0),
    .row_outbuf_i_5_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_ce0),
    .row_outbuf_i_5_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_we0),
    .row_outbuf_i_5_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_5_d0),
    .row_outbuf_i_4_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_address0),
    .row_outbuf_i_4_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_ce0),
    .row_outbuf_i_4_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_we0),
    .row_outbuf_i_4_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_4_d0),
    .row_outbuf_i_3_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_address0),
    .row_outbuf_i_3_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_ce0),
    .row_outbuf_i_3_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_we0),
    .row_outbuf_i_3_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_3_d0),
    .row_outbuf_i_2_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_address0),
    .row_outbuf_i_2_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_ce0),
    .row_outbuf_i_2_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_we0),
    .row_outbuf_i_2_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_2_d0),
    .row_outbuf_i_1_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_address0),
    .row_outbuf_i_1_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_ce0),
    .row_outbuf_i_1_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_we0),
    .row_outbuf_i_1_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_1_d0),
    .row_outbuf_i_0_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_address0),
    .row_outbuf_i_0_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_ce0),
    .row_outbuf_i_0_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_we0),
    .row_outbuf_i_0_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_0_d0),
    .row_outbuf_i_7_address0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_address0),
    .row_outbuf_i_7_ce0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_ce0),
    .row_outbuf_i_7_we0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_we0),
    .row_outbuf_i_7_d0(Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_d0)
);

dct_Loop_Xpose_Row_Outer_Loop_proc Loop_Xpose_Row_Outer_Loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start),
    .ap_done(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done),
    .ap_continue(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue),
    .ap_idle(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle),
    .ap_ready(Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready),
    .col_inbuf_i_7_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_address0),
    .col_inbuf_i_7_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_ce0),
    .col_inbuf_i_7_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_we0),
    .col_inbuf_i_7_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_7_d0),
    .col_inbuf_i_6_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_address0),
    .col_inbuf_i_6_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_ce0),
    .col_inbuf_i_6_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_we0),
    .col_inbuf_i_6_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_6_d0),
    .col_inbuf_i_5_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_address0),
    .col_inbuf_i_5_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_ce0),
    .col_inbuf_i_5_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_we0),
    .col_inbuf_i_5_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_5_d0),
    .col_inbuf_i_4_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_address0),
    .col_inbuf_i_4_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_ce0),
    .col_inbuf_i_4_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_we0),
    .col_inbuf_i_4_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_4_d0),
    .col_inbuf_i_3_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_address0),
    .col_inbuf_i_3_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_ce0),
    .col_inbuf_i_3_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_we0),
    .col_inbuf_i_3_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_3_d0),
    .col_inbuf_i_2_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_address0),
    .col_inbuf_i_2_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_ce0),
    .col_inbuf_i_2_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_we0),
    .col_inbuf_i_2_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_2_d0),
    .col_inbuf_i_1_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_address0),
    .col_inbuf_i_1_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_ce0),
    .col_inbuf_i_1_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_we0),
    .col_inbuf_i_1_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_1_d0),
    .col_inbuf_i_0_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_address0),
    .col_inbuf_i_0_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_ce0),
    .col_inbuf_i_0_we0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_we0),
    .col_inbuf_i_0_d0(Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_d0),
    .row_outbuf_i_0_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_address0),
    .row_outbuf_i_0_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_0_ce0),
    .row_outbuf_i_0_q0(row_outbuf_t_q0),
    .row_outbuf_i_1_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_address0),
    .row_outbuf_i_1_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_1_ce0),
    .row_outbuf_i_1_q0(row_outbuf_1_t_q0),
    .row_outbuf_i_2_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_address0),
    .row_outbuf_i_2_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_2_ce0),
    .row_outbuf_i_2_q0(row_outbuf_2_t_q0),
    .row_outbuf_i_3_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_address0),
    .row_outbuf_i_3_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_3_ce0),
    .row_outbuf_i_3_q0(row_outbuf_3_t_q0),
    .row_outbuf_i_4_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_address0),
    .row_outbuf_i_4_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_4_ce0),
    .row_outbuf_i_4_q0(row_outbuf_4_t_q0),
    .row_outbuf_i_5_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_address0),
    .row_outbuf_i_5_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_5_ce0),
    .row_outbuf_i_5_q0(row_outbuf_5_t_q0),
    .row_outbuf_i_6_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_address0),
    .row_outbuf_i_6_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_6_ce0),
    .row_outbuf_i_6_q0(row_outbuf_6_t_q0),
    .row_outbuf_i_7_address0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_address0),
    .row_outbuf_i_7_ce0(Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_7_ce0),
    .row_outbuf_i_7_q0(row_outbuf_7_t_q0)
);

dct_Loop_Col_DCT_Loop_proc Loop_Col_DCT_Loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Col_DCT_Loop_proc_U0_ap_start),
    .ap_done(Loop_Col_DCT_Loop_proc_U0_ap_done),
    .ap_continue(Loop_Col_DCT_Loop_proc_U0_ap_continue),
    .ap_idle(Loop_Col_DCT_Loop_proc_U0_ap_idle),
    .ap_ready(Loop_Col_DCT_Loop_proc_U0_ap_ready),
    .col_inbuf_i_0_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_address0),
    .col_inbuf_i_0_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_0_ce0),
    .col_inbuf_i_0_q0(col_inbuf_t_q0),
    .col_inbuf_i_1_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_address0),
    .col_inbuf_i_1_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_1_ce0),
    .col_inbuf_i_1_q0(col_inbuf_1_t_q0),
    .col_inbuf_i_2_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_address0),
    .col_inbuf_i_2_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_2_ce0),
    .col_inbuf_i_2_q0(col_inbuf_2_t_q0),
    .col_inbuf_i_3_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_address0),
    .col_inbuf_i_3_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_3_ce0),
    .col_inbuf_i_3_q0(col_inbuf_3_t_q0),
    .col_inbuf_i_4_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_address0),
    .col_inbuf_i_4_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_4_ce0),
    .col_inbuf_i_4_q0(col_inbuf_4_t_q0),
    .col_inbuf_i_5_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_address0),
    .col_inbuf_i_5_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_5_ce0),
    .col_inbuf_i_5_q0(col_inbuf_5_t_q0),
    .col_inbuf_i_6_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_address0),
    .col_inbuf_i_6_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_6_ce0),
    .col_inbuf_i_6_q0(col_inbuf_6_t_q0),
    .col_inbuf_i_7_address0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_address0),
    .col_inbuf_i_7_ce0(Loop_Col_DCT_Loop_proc_U0_col_inbuf_i_7_ce0),
    .col_inbuf_i_7_q0(col_inbuf_7_t_q0),
    .col_outbuf_i_6_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_address0),
    .col_outbuf_i_6_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_ce0),
    .col_outbuf_i_6_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_we0),
    .col_outbuf_i_6_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_6_d0),
    .col_outbuf_i_5_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_address0),
    .col_outbuf_i_5_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_ce0),
    .col_outbuf_i_5_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_we0),
    .col_outbuf_i_5_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_5_d0),
    .col_outbuf_i_4_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_address0),
    .col_outbuf_i_4_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_ce0),
    .col_outbuf_i_4_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_we0),
    .col_outbuf_i_4_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_4_d0),
    .col_outbuf_i_3_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_address0),
    .col_outbuf_i_3_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_ce0),
    .col_outbuf_i_3_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_we0),
    .col_outbuf_i_3_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_3_d0),
    .col_outbuf_i_2_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_address0),
    .col_outbuf_i_2_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_ce0),
    .col_outbuf_i_2_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_we0),
    .col_outbuf_i_2_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_2_d0),
    .col_outbuf_i_1_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_address0),
    .col_outbuf_i_1_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_ce0),
    .col_outbuf_i_1_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_we0),
    .col_outbuf_i_1_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_1_d0),
    .col_outbuf_i_0_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_address0),
    .col_outbuf_i_0_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_ce0),
    .col_outbuf_i_0_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_we0),
    .col_outbuf_i_0_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_0_d0),
    .col_outbuf_i_7_address0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_address0),
    .col_outbuf_i_7_ce0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_ce0),
    .col_outbuf_i_7_we0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_we0),
    .col_outbuf_i_7_d0(Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_d0)
);

dct_Loop_Xpose_Col_Outer_Loop_proc Loop_Xpose_Col_Outer_Loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start),
    .ap_done(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done),
    .ap_continue(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue),
    .ap_idle(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle),
    .ap_ready(Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready),
    .buf_2d_out_7_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_address0),
    .buf_2d_out_7_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_ce0),
    .buf_2d_out_7_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_we0),
    .buf_2d_out_7_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_7_d0),
    .buf_2d_out_6_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_address0),
    .buf_2d_out_6_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_ce0),
    .buf_2d_out_6_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_we0),
    .buf_2d_out_6_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_6_d0),
    .buf_2d_out_5_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_address0),
    .buf_2d_out_5_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_ce0),
    .buf_2d_out_5_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_we0),
    .buf_2d_out_5_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_5_d0),
    .buf_2d_out_4_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_address0),
    .buf_2d_out_4_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_ce0),
    .buf_2d_out_4_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_we0),
    .buf_2d_out_4_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_4_d0),
    .buf_2d_out_3_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_address0),
    .buf_2d_out_3_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_ce0),
    .buf_2d_out_3_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_we0),
    .buf_2d_out_3_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_3_d0),
    .buf_2d_out_2_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_address0),
    .buf_2d_out_2_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_ce0),
    .buf_2d_out_2_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_we0),
    .buf_2d_out_2_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_2_d0),
    .buf_2d_out_1_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_address0),
    .buf_2d_out_1_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_ce0),
    .buf_2d_out_1_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_we0),
    .buf_2d_out_1_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_1_d0),
    .buf_2d_out_0_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_address0),
    .buf_2d_out_0_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_ce0),
    .buf_2d_out_0_we0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_we0),
    .buf_2d_out_0_d0(Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_d0),
    .col_outbuf_i_0_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_address0),
    .col_outbuf_i_0_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_0_ce0),
    .col_outbuf_i_0_q0(col_outbuf_t_q0),
    .col_outbuf_i_1_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_address0),
    .col_outbuf_i_1_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_1_ce0),
    .col_outbuf_i_1_q0(col_outbuf_1_t_q0),
    .col_outbuf_i_2_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_address0),
    .col_outbuf_i_2_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_2_ce0),
    .col_outbuf_i_2_q0(col_outbuf_2_t_q0),
    .col_outbuf_i_3_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_address0),
    .col_outbuf_i_3_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_3_ce0),
    .col_outbuf_i_3_q0(col_outbuf_3_t_q0),
    .col_outbuf_i_4_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_address0),
    .col_outbuf_i_4_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_4_ce0),
    .col_outbuf_i_4_q0(col_outbuf_4_t_q0),
    .col_outbuf_i_5_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_address0),
    .col_outbuf_i_5_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_5_ce0),
    .col_outbuf_i_5_q0(col_outbuf_5_t_q0),
    .col_outbuf_i_6_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_address0),
    .col_outbuf_i_6_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_6_ce0),
    .col_outbuf_i_6_q0(col_outbuf_6_t_q0),
    .col_outbuf_i_7_address0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_address0),
    .col_outbuf_i_7_ce0(Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_7_ce0),
    .col_outbuf_i_7_q0(col_outbuf_7_t_q0)
);

dct_write_data write_data_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(write_data_U0_ap_start),
    .ap_done(write_data_U0_ap_done),
    .ap_continue(write_data_U0_ap_continue),
    .ap_idle(write_data_U0_ap_idle),
    .ap_ready(write_data_U0_ap_ready),
    .buf_0_address0(write_data_U0_buf_0_address0),
    .buf_0_ce0(write_data_U0_buf_0_ce0),
    .buf_0_q0(buf_2d_out_t_q0),
    .buf_1_address0(write_data_U0_buf_1_address0),
    .buf_1_ce0(write_data_U0_buf_1_ce0),
    .buf_1_q0(buf_2d_out_8_t_q0),
    .buf_2_address0(write_data_U0_buf_2_address0),
    .buf_2_ce0(write_data_U0_buf_2_ce0),
    .buf_2_q0(buf_2d_out_9_t_q0),
    .buf_3_address0(write_data_U0_buf_3_address0),
    .buf_3_ce0(write_data_U0_buf_3_ce0),
    .buf_3_q0(buf_2d_out_10_t_q0),
    .buf_4_address0(write_data_U0_buf_4_address0),
    .buf_4_ce0(write_data_U0_buf_4_ce0),
    .buf_4_q0(buf_2d_out_11_t_q0),
    .buf_5_address0(write_data_U0_buf_5_address0),
    .buf_5_ce0(write_data_U0_buf_5_ce0),
    .buf_5_q0(buf_2d_out_12_t_q0),
    .buf_6_address0(write_data_U0_buf_6_address0),
    .buf_6_ce0(write_data_U0_buf_6_ce0),
    .buf_6_q0(buf_2d_out_13_t_q0),
    .buf_7_address0(write_data_U0_buf_7_address0),
    .buf_7_ce0(write_data_U0_buf_7_ce0),
    .buf_7_q0(buf_2d_out_14_t_q0),
    .output_r_address0(write_data_U0_output_r_address0),
    .output_r_ce0(write_data_U0_output_r_ce0),
    .output_r_we0(write_data_U0_output_r_we0),
    .output_r_d0(write_data_U0_output_r_d0),
    .output_r_address1(write_data_U0_output_r_address1),
    .output_r_ce1(write_data_U0_output_r_ce1),
    .output_r_we1(write_data_U0_output_r_we1),
    .output_r_d1(write_data_U0_output_r_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_buf_2d_in_14 <= 1'b0;
    end else begin
        if (((read_data_U0_ap_done & read_data_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_buf_2d_in_14 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_buf_2d_in_14 <= ap_sync_channel_write_buf_2d_in_14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_buf_2d_out <= 1'b0;
    end else begin
        if (((Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done & Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_buf_2d_out <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_buf_2d_out <= ap_sync_channel_write_buf_2d_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_col_inbuf <= 1'b0;
    end else begin
        if (((Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done & Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_col_inbuf <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_col_inbuf <= ap_sync_channel_write_col_inbuf;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_col_outbuf_7 <= 1'b0;
    end else begin
        if (((Loop_Col_DCT_Loop_proc_U0_ap_done & Loop_Col_DCT_Loop_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_col_outbuf_7 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_col_outbuf_7 <= ap_sync_channel_write_col_outbuf_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_row_outbuf_7 <= 1'b0;
    end else begin
        if (((Loop_Row_DCT_Loop_proc_U0_ap_done & Loop_Row_DCT_Loop_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_row_outbuf_7 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_row_outbuf_7 <= ap_sync_channel_write_row_outbuf_7;
        end
    end
end

assign Loop_Col_DCT_Loop_proc_U0_ap_continue = ap_sync_channel_write_col_outbuf_7;

assign Loop_Col_DCT_Loop_proc_U0_ap_start = col_inbuf_t_empty_n;

assign Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_full_n = col_outbuf_7_i_full_n;

assign Loop_Row_DCT_Loop_proc_U0_ap_continue = ap_sync_channel_write_row_outbuf_7;

assign Loop_Row_DCT_Loop_proc_U0_ap_start = buf_2d_in_14_t_empty_n;

assign Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_full_n = row_outbuf_7_i_full_n;

assign Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue = ap_sync_channel_write_buf_2d_out;

assign Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start = col_outbuf_7_t_empty_n;

assign Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_full_n = buf_2d_out_i_full_n;

assign Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue = ap_sync_channel_write_col_inbuf;

assign Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start = row_outbuf_7_t_empty_n;

assign Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_full_n = col_inbuf_i_full_n;

assign ap_channel_done_buf_2d_in_14 = (read_data_U0_ap_done & (ap_sync_reg_channel_write_buf_2d_in_14 ^ 1'b1));

assign ap_channel_done_buf_2d_out = ((ap_sync_reg_channel_write_buf_2d_out ^ 1'b1) & Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done);

assign ap_channel_done_col_inbuf = ((ap_sync_reg_channel_write_col_inbuf ^ 1'b1) & Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done);

assign ap_channel_done_col_outbuf_7 = ((ap_sync_reg_channel_write_col_outbuf_7 ^ 1'b1) & Loop_Col_DCT_Loop_proc_U0_ap_done);

assign ap_channel_done_row_outbuf_7 = ((ap_sync_reg_channel_write_row_outbuf_7 ^ 1'b1) & Loop_Row_DCT_Loop_proc_U0_ap_done);

assign ap_done = write_data_U0_ap_done;

assign ap_idle = (write_data_U0_ap_idle & read_data_U0_ap_idle & (buf_2d_out_t_empty_n ^ 1'b1) & (col_outbuf_7_t_empty_n ^ 1'b1) & (col_inbuf_t_empty_n ^ 1'b1) & (row_outbuf_7_t_empty_n ^ 1'b1) & (buf_2d_in_14_t_empty_n ^ 1'b1) & Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle & Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle & Loop_Row_DCT_Loop_proc_U0_ap_idle & Loop_Col_DCT_Loop_proc_U0_ap_idle);

assign ap_ready = read_data_U0_ap_ready;

assign ap_sync_channel_write_buf_2d_in_14 = ((read_data_U0_buf_7_full_n & ap_channel_done_buf_2d_in_14) | ap_sync_reg_channel_write_buf_2d_in_14);

assign ap_sync_channel_write_buf_2d_out = ((ap_channel_done_buf_2d_out & Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_0_full_n) | ap_sync_reg_channel_write_buf_2d_out);

assign ap_sync_channel_write_col_inbuf = ((ap_channel_done_col_inbuf & Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_i_0_full_n) | ap_sync_reg_channel_write_col_inbuf);

assign ap_sync_channel_write_col_outbuf_7 = ((ap_channel_done_col_outbuf_7 & Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_7_full_n) | ap_sync_reg_channel_write_col_outbuf_7);

assign ap_sync_channel_write_row_outbuf_7 = ((ap_channel_done_row_outbuf_7 & Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_7_full_n) | ap_sync_reg_channel_write_row_outbuf_7);

assign input_r_address0 = read_data_U0_input_r_address0;

assign input_r_address1 = read_data_U0_input_r_address1;

assign input_r_ce0 = read_data_U0_input_r_ce0;

assign input_r_ce1 = read_data_U0_input_r_ce1;

assign input_r_d0 = 16'd0;

assign input_r_d1 = 16'd0;

assign input_r_we0 = 1'b0;

assign input_r_we1 = 1'b0;

assign output_r_address0 = write_data_U0_output_r_address0;

assign output_r_address1 = write_data_U0_output_r_address1;

assign output_r_ce0 = write_data_U0_output_r_ce0;

assign output_r_ce1 = write_data_U0_output_r_ce1;

assign output_r_d0 = write_data_U0_output_r_d0;

assign output_r_d1 = write_data_U0_output_r_d1;

assign output_r_we0 = write_data_U0_output_r_we0;

assign output_r_we1 = write_data_U0_output_r_we1;

assign read_data_U0_ap_continue = ap_sync_channel_write_buf_2d_in_14;

assign read_data_U0_ap_start = ap_start;

assign read_data_U0_buf_7_full_n = buf_2d_in_14_i_full_n;

assign write_data_U0_ap_continue = 1'b1;

assign write_data_U0_ap_start = buf_2d_out_t_empty_n;

endmodule //dct
