[hls]
relative_roots=C:/Users/duong/Desktop/xup_high_level_synthesis_design_flow-main/source/lab1/matrixmul
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=matrixmul/Col 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=matrixmul/Row  


