[hls]
relative_roots=C:/Users/duong/Desktop/xup_high_level_synthesis_design_flow-main/source/lab3/dct_array_partition
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=dct_2d/row_outbuf dim=1 type=cyclic factor=3 variable=row_outbuf
syn.directive.array_partition=dct_2d/col_inbuf dim=1 type=complete variable=col_inbuf


