// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_yuv_channels_ch1_dout,
        p_yuv_channels_ch1_empty_n,
        p_yuv_channels_ch1_read,
        p_yuv_channels_ch1_num_data_valid,
        p_yuv_channels_ch1_fifo_cap,
        p_yuv_channels_ch2_dout,
        p_yuv_channels_ch2_empty_n,
        p_yuv_channels_ch2_read,
        p_yuv_channels_ch2_num_data_valid,
        p_yuv_channels_ch2_fifo_cap,
        p_yuv_channels_ch3_dout,
        p_yuv_channels_ch3_empty_n,
        p_yuv_channels_ch3_read,
        p_yuv_channels_ch3_num_data_valid,
        p_yuv_channels_ch3_fifo_cap,
        p_scale_channels_ch1_din,
        p_scale_channels_ch1_full_n,
        p_scale_channels_ch1_write,
        p_scale_channels_ch1_num_data_valid,
        p_scale_channels_ch1_fifo_cap,
        p_scale_channels_ch2_din,
        p_scale_channels_ch2_full_n,
        p_scale_channels_ch2_write,
        p_scale_channels_ch2_num_data_valid,
        p_scale_channels_ch2_fifo_cap,
        p_scale_channels_ch3_din,
        p_scale_channels_ch3_full_n,
        p_scale_channels_ch3_write,
        p_scale_channels_ch3_num_data_valid,
        p_scale_channels_ch3_fifo_cap,
        bound,
        zext_ln174,
        zext_ln175,
        zext_ln176
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_yuv_channels_ch1_dout;
input   p_yuv_channels_ch1_empty_n;
output   p_yuv_channels_ch1_read;
input  [22:0] p_yuv_channels_ch1_num_data_valid;
input  [22:0] p_yuv_channels_ch1_fifo_cap;
input  [7:0] p_yuv_channels_ch2_dout;
input   p_yuv_channels_ch2_empty_n;
output   p_yuv_channels_ch2_read;
input  [22:0] p_yuv_channels_ch2_num_data_valid;
input  [22:0] p_yuv_channels_ch2_fifo_cap;
input  [7:0] p_yuv_channels_ch3_dout;
input   p_yuv_channels_ch3_empty_n;
output   p_yuv_channels_ch3_read;
input  [22:0] p_yuv_channels_ch3_num_data_valid;
input  [22:0] p_yuv_channels_ch3_fifo_cap;
output  [7:0] p_scale_channels_ch1_din;
input   p_scale_channels_ch1_full_n;
output   p_scale_channels_ch1_write;
input  [31:0] p_scale_channels_ch1_num_data_valid;
input  [31:0] p_scale_channels_ch1_fifo_cap;
output  [7:0] p_scale_channels_ch2_din;
input   p_scale_channels_ch2_full_n;
output   p_scale_channels_ch2_write;
input  [31:0] p_scale_channels_ch2_num_data_valid;
input  [31:0] p_scale_channels_ch2_fifo_cap;
output  [7:0] p_scale_channels_ch3_din;
input   p_scale_channels_ch3_full_n;
output   p_scale_channels_ch3_write;
input  [31:0] p_scale_channels_ch3_num_data_valid;
input  [31:0] p_scale_channels_ch3_fifo_cap;
input  [31:0] bound;
input  [7:0] zext_ln174;
input  [7:0] zext_ln175;
input  [7:0] zext_ln176;

reg ap_idle;
reg p_yuv_channels_ch1_read;
reg p_yuv_channels_ch2_read;
reg p_yuv_channels_ch3_read;
reg p_scale_channels_ch1_write;
reg p_scale_channels_ch2_write;
reg p_scale_channels_ch3_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
wire   [0:0] icmp_ln164_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    p_yuv_channels_ch1_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    p_yuv_channels_ch2_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    p_yuv_channels_ch3_blk_n;
wire    ap_block_pp0_stage0_grp3;
reg    p_scale_channels_ch1_blk_n;
reg    p_scale_channels_ch2_blk_n;
reg    p_scale_channels_ch3_blk_n;
wire   [14:0] zext_ln176_cast_fu_133_p1;
reg   [14:0] zext_ln176_cast_reg_234;
reg    ap_block_pp0_stage0_11001_grp3;
wire   [14:0] zext_ln175_cast_fu_137_p1;
reg   [14:0] zext_ln175_cast_reg_239;
reg    ap_block_pp0_stage0_11001_grp2;
wire   [14:0] zext_ln174_cast_fu_141_p1;
reg   [14:0] zext_ln174_cast_reg_244;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] trunc_ln_reg_253;
reg   [7:0] trunc_ln1_reg_258;
reg   [7:0] trunc_ln2_reg_263;
reg   [31:0] indvar_flatten_fu_66;
wire   [31:0] add_ln164_fu_159_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_block_pp0_stage0_01001_grp3;
wire   [7:0] mul_ln174_fu_174_p0;
wire   [7:0] mul_ln174_fu_174_p1;
wire   [7:0] mul_ln175_fu_183_p0;
wire   [7:0] mul_ln175_fu_183_p1;
wire   [7:0] mul_ln176_fu_192_p0;
wire   [7:0] mul_ln176_fu_192_p1;
wire   [14:0] mul_ln174_fu_174_p2;
wire   [14:0] mul_ln175_fu_183_p2;
wire   [14:0] mul_ln176_fu_192_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] mul_ln174_fu_174_p00;
wire   [14:0] mul_ln175_fu_183_p00;
wire   [14:0] mul_ln176_fu_192_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 indvar_flatten_fu_66 = 32'd0;
#0 ap_done_reg = 1'b0;
end

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U36(
    .din0(mul_ln174_fu_174_p0),
    .din1(mul_ln174_fu_174_p1),
    .dout(mul_ln174_fu_174_p2)
);

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U37(
    .din0(mul_ln175_fu_183_p0),
    .din1(mul_ln175_fu_183_p1),
    .dout(mul_ln175_fu_183_p2)
);

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U38(
    .din0(mul_ln176_fu_192_p0),
    .din1(mul_ln176_fu_192_p1),
    .dout(mul_ln176_fu_192_p2)
);

yuv_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln164_fu_153_p2 == 1'd0))) begin
            indvar_flatten_fu_66 <= add_ln164_fu_159_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_66 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln1_reg_258 <= {{mul_ln175_fu_183_p2[14:7]}};
        zext_ln175_cast_reg_239[7 : 0] <= zext_ln175_cast_fu_137_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln2_reg_263 <= {{mul_ln176_fu_192_p2[14:7]}};
        zext_ln176_cast_reg_234[7 : 0] <= zext_ln176_cast_fu_133_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln_reg_253 <= {{mul_ln174_fu_174_p2[14:7]}};
        zext_ln174_cast_reg_244[7 : 0] <= zext_ln174_cast_fu_141_p1[7 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln164_fu_153_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 32'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch1_blk_n = p_scale_channels_ch1_full_n;
    end else begin
        p_scale_channels_ch1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch1_write = 1'b1;
    end else begin
        p_scale_channels_ch1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch2_blk_n = p_scale_channels_ch2_full_n;
    end else begin
        p_scale_channels_ch2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch2_write = 1'b1;
    end else begin
        p_scale_channels_ch2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch3_blk_n = p_scale_channels_ch3_full_n;
    end else begin
        p_scale_channels_ch3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_scale_channels_ch3_write = 1'b1;
    end else begin
        p_scale_channels_ch3_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch1_blk_n = p_yuv_channels_ch1_empty_n;
    end else begin
        p_yuv_channels_ch1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch1_read = 1'b1;
    end else begin
        p_yuv_channels_ch1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch2_blk_n = p_yuv_channels_ch2_empty_n;
    end else begin
        p_yuv_channels_ch2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch2_read = 1'b1;
    end else begin
        p_yuv_channels_ch2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch3_blk_n = p_yuv_channels_ch3_empty_n;
    end else begin
        p_yuv_channels_ch3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_yuv_channels_ch3_read = 1'b1;
    end else begin
        p_yuv_channels_ch3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln164_fu_159_p2 = (ap_sig_allocacmp_indvar_flatten_load + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_scale_channels_ch1_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_yuv_channels_ch1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_scale_channels_ch2_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_yuv_channels_ch2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp3 = (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_scale_channels_ch3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_yuv_channels_ch3_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_yuv_channels_ch3_empty_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_yuv_channels_ch2_empty_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_yuv_channels_ch1_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_scale_channels_ch3_full_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_scale_channels_ch2_full_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_scale_channels_ch1_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_scale_channels_ch1_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_yuv_channels_ch1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_scale_channels_ch2_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_yuv_channels_ch2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_scale_channels_ch3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_yuv_channels_ch3_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_yuv_channels_ch3_empty_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_yuv_channels_ch2_empty_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_yuv_channels_ch1_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_scale_channels_ch3_full_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_scale_channels_ch2_full_n == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_scale_channels_ch1_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_scale_channels_ch1_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (p_yuv_channels_ch1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_scale_channels_ch2_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (p_yuv_channels_ch2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_scale_channels_ch3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (p_yuv_channels_ch3_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln164_fu_153_p2 = ((ap_sig_allocacmp_indvar_flatten_load == bound) ? 1'b1 : 1'b0);

assign mul_ln174_fu_174_p0 = mul_ln174_fu_174_p00;

assign mul_ln174_fu_174_p00 = p_yuv_channels_ch1_dout;

assign mul_ln174_fu_174_p1 = zext_ln174_cast_reg_244;

assign mul_ln175_fu_183_p0 = mul_ln175_fu_183_p00;

assign mul_ln175_fu_183_p00 = p_yuv_channels_ch2_dout;

assign mul_ln175_fu_183_p1 = zext_ln175_cast_reg_239;

assign mul_ln176_fu_192_p0 = mul_ln176_fu_192_p00;

assign mul_ln176_fu_192_p00 = p_yuv_channels_ch3_dout;

assign mul_ln176_fu_192_p1 = zext_ln176_cast_reg_234;

assign p_scale_channels_ch1_din = trunc_ln_reg_253;

assign p_scale_channels_ch2_din = trunc_ln1_reg_258;

assign p_scale_channels_ch3_din = trunc_ln2_reg_263;

assign zext_ln174_cast_fu_141_p1 = zext_ln174;

assign zext_ln175_cast_fu_137_p1 = zext_ln175;

assign zext_ln176_cast_fu_133_p1 = zext_ln176;

always @ (posedge ap_clk) begin
    zext_ln176_cast_reg_234[14:8] <= 7'b0000000;
    zext_ln175_cast_reg_239[14:8] <= 7'b0000000;
    zext_ln174_cast_reg_244[14:8] <= 7'b0000000;
end

endmodule //yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y
