-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_yuv_filter_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mul_ln30 : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    in_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch1_ce0 : OUT STD_LOGIC;
    in_channels_ch1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch2_ce0 : OUT STD_LOGIC;
    in_channels_ch2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch3_ce0 : OUT STD_LOGIC;
    in_channels_ch3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch1_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch1_we0 : OUT STD_LOGIC;
    p_yuv_channels_ch1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch2_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch2_we0 : OUT STD_LOGIC;
    p_yuv_channels_ch2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch3_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch3_we0 : OUT STD_LOGIC;
    p_yuv_channels_ch3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of yuv_filter_yuv_filter_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv16_FFB6 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110110110";
    constant ap_const_lv16_FFA2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv15_80 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_80 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv13_19 : STD_LOGIC_VECTOR (12 downto 0) := "0000000011001";
    constant ap_const_lv13_80 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_const_lv15_7FDA : STD_LOGIC_VECTOR (14 downto 0) := "111111111011010";
    constant ap_const_lv15_7A : STD_LOGIC_VECTOR (14 downto 0) := "000000001111010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln75_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln80_1_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_reg_648 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_reg_648_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_reg_648_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_reg_648_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_reg_648_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal R_reg_666 : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_666_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_666_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_672 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_672_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_672_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln83_fu_344_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln83_4_fu_368_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln83_4_reg_695 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln84_1_fu_374_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln85_1_fu_380_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_710 : STD_LOGIC_VECTOR (7 downto 0);
    signal bit_sel1_reg_715 : STD_LOGIC_VECTOR (0 downto 0);
    signal part_sel3_reg_720 : STD_LOGIC_VECTOR (6 downto 0);
    signal bit_sel_reg_725 : STD_LOGIC_VECTOR (0 downto 0);
    signal part_sel_reg_730 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal y_fu_112 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln78_fu_328_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal x_fu_116 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln75_fu_274_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln75_1_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (31 downto 0);
    signal in_channels_ch1_ce0_local : STD_LOGIC;
    signal in_channels_ch3_ce0_local : STD_LOGIC;
    signal in_channels_ch2_ce0_local : STD_LOGIC;
    signal p_yuv_channels_ch1_we0_local : STD_LOGIC;
    signal Y_fu_559_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_yuv_channels_ch1_ce0_local : STD_LOGIC;
    signal p_yuv_channels_ch2_we0_local : STD_LOGIC;
    signal U_fu_570_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_yuv_channels_ch2_ce0_local : STD_LOGIC;
    signal p_yuv_channels_ch3_we0_local : STD_LOGIC;
    signal V_fu_583_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_yuv_channels_ch3_ce0_local : STD_LOGIC;
    signal icmp_ln78_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_fu_255_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln80_fu_282_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln80_1_fu_294_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl4_fu_286_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal p_shl5_fu_298_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln60_fu_266_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln78_1_fu_306_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln80_fu_312_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln80_fu_316_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_9_fu_356_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln83_7_fu_364_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln83_1_fu_352_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln84_1_fu_374_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln84_1_fu_374_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln85_1_fu_380_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln85_1_fu_380_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_386_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_8_fu_397_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln83_3_fu_393_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln83_4_fu_404_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln83_3_fu_408_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln83_5_fu_414_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_591_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln83_6_fu_423_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln83_fu_418_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln83_2_fu_426_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_449_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl8_fu_442_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln84_1_fu_456_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln84_fu_460_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln84_1_fu_466_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln84_fu_472_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_600_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln84_2_fu_476_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln84_2_fu_476_p2 : signal is "no";
    signal zext_ln85_1_fu_499_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_11_fu_509_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln85_fu_503_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln85_2_fu_516_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln85_1_fu_520_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln85_1_fu_526_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln85_fu_532_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_609_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln85_2_fu_536_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp of add_ln85_2_fu_536_p2 : signal is "no";
    signal xor_ln84_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln85_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_591_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_591_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_591_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_600_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_600_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_609_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_609_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_591_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_mul_8ns_8s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_5ns_8ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_7s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_7ns_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_8s_16_1_1_U1 : component yuv_filter_mul_8ns_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln84_1_fu_374_p0,
        din1 => mul_ln84_1_fu_374_p1,
        dout => mul_ln84_1_fu_374_p2);

    mul_8ns_8s_16_1_1_U2 : component yuv_filter_mul_8ns_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln85_1_fu_380_p0,
        din1 => mul_ln85_1_fu_380_p1,
        dout => mul_ln85_1_fu_380_p2);

    mac_muladd_8ns_5ns_8ns_13_4_1_U3 : component yuv_filter_mac_muladd_8ns_5ns_8ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_591_p0,
        din1 => grp_fu_591_p1,
        din2 => grp_fu_591_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_591_p3);

    mac_muladd_8ns_7s_16s_16_4_1_U4 : component yuv_filter_mac_muladd_8ns_7s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_600_p0,
        din1 => grp_fu_600_p1,
        din2 => mul_ln84_1_fu_374_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_600_p3);

    mac_muladd_8ns_7ns_16s_16_4_1_U5 : component yuv_filter_mac_muladd_8ns_7ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_609_p0,
        din1 => grp_fu_609_p1,
        din2 => mul_ln85_1_fu_380_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_609_p3);

    flow_control_loop_pipe_sequential_init_U : component yuv_filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln75_fu_232_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_120 <= add_ln75_1_fu_238_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_120 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_116 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_fu_116 <= select_ln75_fu_274_p3;
                end if;
            end if; 
        end if;
    end process;

    y_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_112 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    y_fu_112 <= add_ln78_fu_328_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                B_reg_672 <= in_channels_ch3_q0;
                B_reg_672_pp0_iter3_reg <= B_reg_672;
                B_reg_672_pp0_iter4_reg <= B_reg_672_pp0_iter3_reg;
                R_reg_666 <= in_channels_ch1_q0;
                R_reg_666_pp0_iter3_reg <= R_reg_666;
                R_reg_666_pp0_iter4_reg <= R_reg_666_pp0_iter3_reg;
                add_ln83_4_reg_695 <= add_ln83_4_fu_368_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                bit_sel1_reg_715 <= add_ln84_2_fu_476_p2(15 downto 15);
                bit_sel_reg_725 <= add_ln85_2_fu_536_p2(15 downto 15);
                part_sel3_reg_720 <= add_ln84_2_fu_476_p2(14 downto 8);
                part_sel_reg_730 <= add_ln85_2_fu_536_p2(14 downto 8);
                trunc_ln_reg_710 <= add_ln83_2_fu_426_p2(15 downto 8);
                    zext_ln80_1_reg_648_pp0_iter2_reg(21 downto 0) <= zext_ln80_1_reg_648(21 downto 0);
                    zext_ln80_1_reg_648_pp0_iter3_reg(21 downto 0) <= zext_ln80_1_reg_648_pp0_iter2_reg(21 downto 0);
                    zext_ln80_1_reg_648_pp0_iter4_reg(21 downto 0) <= zext_ln80_1_reg_648_pp0_iter3_reg(21 downto 0);
                    zext_ln80_1_reg_648_pp0_iter5_reg(21 downto 0) <= zext_ln80_1_reg_648_pp0_iter4_reg(21 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    zext_ln80_1_reg_648(21 downto 0) <= zext_ln80_1_fu_322_p1(21 downto 0);
            end if;
        end if;
    end process;
    zext_ln80_1_reg_648(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln80_1_reg_648_pp0_iter2_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln80_1_reg_648_pp0_iter3_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln80_1_reg_648_pp0_iter4_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln80_1_reg_648_pp0_iter5_reg(63 downto 22) <= "000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    U_fu_570_p3 <= (xor_ln84_fu_565_p2 & part_sel3_reg_720);
    V_fu_583_p3 <= (xor_ln85_fu_578_p2 & part_sel_reg_730);
    Y_fu_559_p2 <= std_logic_vector(unsigned(trunc_ln_reg_710) + unsigned(ap_const_lv8_10));
    add_ln75_1_fu_238_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv32_1));
    add_ln75_fu_255_p2 <= std_logic_vector(unsigned(x_fu_116) + unsigned(ap_const_lv16_1));
    add_ln78_1_fu_306_p2 <= std_logic_vector(unsigned(p_shl4_fu_286_p3) + unsigned(p_shl5_fu_298_p3));
    add_ln78_fu_328_p2 <= std_logic_vector(unsigned(select_ln60_fu_266_p3) + unsigned(ap_const_lv16_1));
    add_ln80_fu_316_p2 <= std_logic_vector(unsigned(add_ln78_1_fu_306_p2) + unsigned(zext_ln80_fu_312_p1));
    add_ln83_2_fu_426_p2 <= std_logic_vector(unsigned(zext_ln83_6_fu_423_p1) + unsigned(add_ln83_fu_418_p2));
    add_ln83_3_fu_408_p2 <= std_logic_vector(unsigned(zext_ln83_3_fu_393_p1) + unsigned(zext_ln83_4_fu_404_p1));
    add_ln83_4_fu_368_p2 <= std_logic_vector(unsigned(zext_ln83_7_fu_364_p1) + unsigned(zext_ln83_1_fu_352_p1));
    add_ln83_fu_418_p2 <= std_logic_vector(unsigned(zext_ln83_5_fu_414_p1) + unsigned(add_ln83_4_reg_695));
    add_ln84_1_fu_466_p2 <= std_logic_vector(unsigned(sub_ln84_fu_460_p2) + unsigned(ap_const_lv15_80));
    add_ln84_2_fu_476_p2 <= std_logic_vector(unsigned(zext_ln84_fu_472_p1) + unsigned(grp_fu_600_p3));
    add_ln85_1_fu_526_p2 <= std_logic_vector(unsigned(sub_ln85_1_fu_520_p2) + unsigned(ap_const_lv14_80));
    add_ln85_2_fu_536_p2 <= std_logic_vector(signed(sext_ln85_fu_532_p1) + signed(grp_fu_609_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln75_fu_232_p2)
    begin
        if (((icmp_ln75_fu_232_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_120;
        end if; 
    end process;

    grp_fu_591_p0 <= grp_fu_591_p00(8 - 1 downto 0);
    grp_fu_591_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch3_q0),13));
    grp_fu_591_p1 <= ap_const_lv13_19(5 - 1 downto 0);
    grp_fu_591_p2 <= ap_const_lv13_80(8 - 1 downto 0);
    grp_fu_600_p0 <= zext_ln83_fu_344_p1(8 - 1 downto 0);
    grp_fu_600_p1 <= ap_const_lv15_7FDA(7 - 1 downto 0);
    grp_fu_609_p0 <= zext_ln83_fu_344_p1(8 - 1 downto 0);
    grp_fu_609_p1 <= ap_const_lv15_7A(7 - 1 downto 0);
    icmp_ln75_fu_232_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = mul_ln30) else "0";
    icmp_ln78_fu_261_p2 <= "1" when (y_fu_112 = height) else "0";
    in_channels_ch1_address0 <= zext_ln80_1_fu_322_p1(22 - 1 downto 0);
    in_channels_ch1_ce0 <= in_channels_ch1_ce0_local;

    in_channels_ch1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_channels_ch1_ce0_local <= ap_const_logic_1;
        else 
            in_channels_ch1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch2_address0 <= zext_ln80_1_reg_648_pp0_iter2_reg(22 - 1 downto 0);
    in_channels_ch2_ce0 <= in_channels_ch2_ce0_local;

    in_channels_ch2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            in_channels_ch2_ce0_local <= ap_const_logic_1;
        else 
            in_channels_ch2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch3_address0 <= zext_ln80_1_fu_322_p1(22 - 1 downto 0);
    in_channels_ch3_ce0 <= in_channels_ch3_ce0_local;

    in_channels_ch3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_channels_ch3_ce0_local <= ap_const_logic_1;
        else 
            in_channels_ch3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln84_1_fu_374_p0 <= zext_ln83_1_fu_352_p1(8 - 1 downto 0);
    mul_ln84_1_fu_374_p1 <= ap_const_lv16_FFB6(8 - 1 downto 0);
    mul_ln85_1_fu_380_p0 <= zext_ln83_1_fu_352_p1(8 - 1 downto 0);
    mul_ln85_1_fu_380_p1 <= ap_const_lv16_FFA2(8 - 1 downto 0);
    p_shl4_fu_286_p3 <= (trunc_ln80_fu_282_p1 & ap_const_lv10_0);
    p_shl5_fu_298_p3 <= (trunc_ln80_1_fu_294_p1 & ap_const_lv8_0);
    p_shl8_fu_442_p3 <= (B_reg_672_pp0_iter4_reg & ap_const_lv7_0);
    p_yuv_channels_ch1_address0 <= zext_ln80_1_reg_648_pp0_iter5_reg(22 - 1 downto 0);
    p_yuv_channels_ch1_ce0 <= p_yuv_channels_ch1_ce0_local;

    p_yuv_channels_ch1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch1_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch1_d0 <= Y_fu_559_p2;
    p_yuv_channels_ch1_we0 <= p_yuv_channels_ch1_we0_local;

    p_yuv_channels_ch1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch1_we0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch2_address0 <= zext_ln80_1_reg_648_pp0_iter5_reg(22 - 1 downto 0);
    p_yuv_channels_ch2_ce0 <= p_yuv_channels_ch2_ce0_local;

    p_yuv_channels_ch2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch2_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch2_d0 <= U_fu_570_p3;
    p_yuv_channels_ch2_we0 <= p_yuv_channels_ch2_we0_local;

    p_yuv_channels_ch2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch2_we0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch3_address0 <= zext_ln80_1_reg_648_pp0_iter5_reg(22 - 1 downto 0);
    p_yuv_channels_ch3_ce0 <= p_yuv_channels_ch3_ce0_local;

    p_yuv_channels_ch3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch3_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch3_d0 <= V_fu_583_p3;
    p_yuv_channels_ch3_we0 <= p_yuv_channels_ch3_we0_local;

    p_yuv_channels_ch3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_yuv_channels_ch3_we0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln60_fu_266_p3 <= 
        ap_const_lv16_0 when (icmp_ln78_fu_261_p2(0) = '1') else 
        y_fu_112;
    select_ln75_fu_274_p3 <= 
        add_ln75_fu_255_p2 when (icmp_ln78_fu_261_p2(0) = '1') else 
        x_fu_116;
        sext_ln85_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln85_1_fu_526_p2),16));

    sub_ln84_fu_460_p2 <= std_logic_vector(unsigned(p_shl8_fu_442_p3) - unsigned(zext_ln84_1_fu_456_p1));
    sub_ln85_1_fu_520_p2 <= std_logic_vector(unsigned(sub_ln85_fu_503_p2) - unsigned(zext_ln85_2_fu_516_p1));
    sub_ln85_fu_503_p2 <= std_logic_vector(unsigned(ap_const_lv14_0) - unsigned(zext_ln85_1_fu_499_p1));
    tmp_10_fu_449_p3 <= (B_reg_672_pp0_iter4_reg & ap_const_lv4_0);
    tmp_11_fu_509_p3 <= (B_reg_672_pp0_iter4_reg & ap_const_lv1_0);
    tmp_8_fu_397_p3 <= (R_reg_666_pp0_iter4_reg & ap_const_lv1_0);
    tmp_9_fu_356_p3 <= (in_channels_ch2_q0 & ap_const_lv7_0);
    tmp_fu_386_p3 <= (R_reg_666_pp0_iter4_reg & ap_const_lv6_0);
    trunc_ln80_1_fu_294_p1 <= select_ln75_fu_274_p3(14 - 1 downto 0);
    trunc_ln80_fu_282_p1 <= select_ln75_fu_274_p3(12 - 1 downto 0);
    xor_ln84_fu_565_p2 <= (bit_sel1_reg_715 xor ap_const_lv1_1);
    xor_ln85_fu_578_p2 <= (bit_sel_reg_725 xor ap_const_lv1_1);
    zext_ln80_1_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln80_fu_316_p2),64));
    zext_ln80_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_fu_266_p3),22));
    zext_ln83_1_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch2_q0),16));
    zext_ln83_3_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_386_p3),15));
    zext_ln83_4_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_397_p3),15));
    zext_ln83_5_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln83_3_fu_408_p2),16));
    zext_ln83_6_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_591_p3),16));
    zext_ln83_7_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_356_p3),16));
    zext_ln83_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch1_q0),15));
    zext_ln84_1_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_449_p3),15));
    zext_ln84_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_1_fu_466_p2),16));
    zext_ln85_1_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_449_p3),14));
    zext_ln85_2_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_509_p3),14));
end behav;
