[hls]
relative_roots=C:/Users/duong/Desktop/xup_high_level_synthesis_design_flow-main/source/lab3/DCT
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=dct/RD_Loop_Col 
syn.directive.pipeline=dct/DCT_Outer_Loop 
syn.directive.pipeline=dct/Xpose_Row_Inner_Loop 
syn.directive.pipeline=dct/Xpose_Col_Inner_Loop 
syn.directive.pipeline=dct/WR_Loop_Col 


