

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "11", "18", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"],
		"CDFG" : "yuv_filter",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40016", "EstimateLatencyMax" : "2457616",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "1", "Name" : "entry_proc_U0"},
			{"ID" : "2", "Name" : "rgb2yuv_U0"}],
		"OutputProcess" : [
			{"ID" : "18", "Name" : "yuv2rgb_U0"}],
		"Port" : [
			{"Name" : "in_channels_ch1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "rgb2yuv_U0", "Port" : "in_channels_ch1"}]},
			{"Name" : "in_channels_ch2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "rgb2yuv_U0", "Port" : "in_channels_ch2"}]},
			{"Name" : "in_channels_ch3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "rgb2yuv_U0", "Port" : "in_channels_ch3"}]},
			{"Name" : "in_width", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "rgb2yuv_U0", "Port" : "in_width"}]},
			{"Name" : "in_height", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "rgb2yuv_U0", "Port" : "in_height"}]},
			{"Name" : "out_channels_ch1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "yuv2rgb_U0", "Port" : "out_channels_ch1"}]},
			{"Name" : "out_channels_ch2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "yuv2rgb_U0", "Port" : "out_channels_ch2"}]},
			{"Name" : "out_channels_ch3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "yuv2rgb_U0", "Port" : "out_channels_ch3"}]},
			{"Name" : "out_width", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "yuv2rgb_U0", "Port" : "out_width"}]},
			{"Name" : "out_height", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "yuv2rgb_U0", "Port" : "out_height"}]},
			{"Name" : "Y_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "U_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "V_scale", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "Y_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "Y_scale_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "26", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "Y_scale_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "U_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "U_scale_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "27", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "U_scale_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "V_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "V_scale_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "28", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "V_scale_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0", "Parent" : "0", "Child" : ["3", "10"],
		"CDFG" : "rgb2yuv",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40009", "EstimateLatencyMax" : "2457609",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_width", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_height", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_channels_ch1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "in_channels_ch1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_channels_ch2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "in_channels_ch2", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_channels_ch3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "in_channels_ch3", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_yuv_channels_ch1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "29", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "p_yuv_channels_ch1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_yuv_channels_ch2", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "30", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "p_yuv_channels_ch2", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_yuv_channels_ch3", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "31", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Port" : "p_yuv_channels_ch3", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_yuv_width", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "32", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_yuv_width_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_height", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "33", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_yuv_height_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76", "Parent" : "2", "Child" : ["4", "5", "6", "7", "8", "9"],
		"CDFG" : "rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40007", "EstimateLatencyMax" : "2457607",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_channels_ch1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_channels_ch2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_channels_ch3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_yuv_channels_ch1", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_channels_ch2", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch2_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_channels_ch3", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch3_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.mac_muladd_8ns_5ns_15s_15_4_1_U7", "Parent" : "3"},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.mac_muladd_8ns_7s_8ns_15_4_1_U8", "Parent" : "3"},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.mac_muladd_8ns_7ns_8ns_15_4_1_U9", "Parent" : "3"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.mac_muladd_8ns_8s_16s_16_4_1_U10", "Parent" : "3"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.mac_muladd_8ns_8s_16s_16_4_1_U11", "Parent" : "3"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.grp_rgb2yuv_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y_fu_76.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.rgb2yuv_U0.mul_16ns_16ns_32_1_1_U24", "Parent" : "2"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0", "Parent" : "0", "Child" : ["12", "17"],
		"CDFG" : "yuv_scale",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40006", "EstimateLatencyMax" : "2457606",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "1",
		"StartFifo" : "start_for_yuv_scale_U0_U",
		"Port" : [
			{"Name" : "p_yuv_width", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "32", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_yuv_width_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_height", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "33", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_yuv_height_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_channels_ch1", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "29", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_yuv_channels_ch1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_yuv_channels_ch2", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "30", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_yuv_channels_ch2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_yuv_channels_ch3", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "31", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_yuv_channels_ch3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_channels_ch1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["18"], "DependentChan" : "34", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_scale_channels_ch1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_channels_ch2", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["18"], "DependentChan" : "35", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_scale_channels_ch2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_channels_ch3", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["18"], "DependentChan" : "36", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Port" : "p_scale_channels_ch3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_width", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["18"], "DependentChan" : "37", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_scale_width_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_height", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["18"], "DependentChan" : "38", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_scale_height_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "Y_scale", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "26", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "Y_scale_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "U_scale", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "27", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "U_scale_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "V_scale", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "28", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "V_scale_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100", "Parent" : "11", "Child" : ["13", "14", "15", "16"],
		"CDFG" : "yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40003", "EstimateLatencyMax" : "2457603",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_yuv_channels_ch1", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_channels_ch2", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch2_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_yuv_channels_ch3", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_yuv_channels_ch3_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "zext_ln174", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln175", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln176", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_scale_channels_ch1", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_channels_ch2", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch2_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_channels_ch3", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch3_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100.mul_8ns_8ns_15_1_1_U36", "Parent" : "12"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100.mul_8ns_8ns_15_1_1_U37", "Parent" : "12"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100.mul_8ns_8ns_15_1_1_U38", "Parent" : "12"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_100.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.yuv_scale_U0.mul_16ns_16ns_32_1_1_U50", "Parent" : "11"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0", "Parent" : "0", "Child" : ["19", "25"],
		"CDFG" : "yuv2rgb",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40009", "EstimateLatencyMax" : "2457609",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "11",
		"StartFifo" : "start_for_yuv2rgb_U0_U",
		"Port" : [
			{"Name" : "p_scale_width", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "37", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_scale_width_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_height", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "38", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "p_scale_height_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_channels_ch1", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "34", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "p_scale_channels_ch1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_channels_ch2", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "35", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "p_scale_channels_ch2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_scale_channels_ch3", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "36", "DependentChanDepth" : "2457600", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "p_scale_channels_ch3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_channels_ch1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "out_channels_ch1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_channels_ch2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "out_channels_ch2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_channels_ch3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Port" : "out_channels_ch3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_width", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "out_height", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74", "Parent" : "18", "Child" : ["20", "21", "22", "23", "24"],
		"CDFG" : "yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40006", "EstimateLatencyMax" : "2457606",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_channels_ch1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_channels_ch2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_channels_ch3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_scale_channels_ch1", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_channels_ch2", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch2_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_scale_channels_ch3", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "p_scale_channels_ch3_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74.mul_8s_9s_17_1_1_U64", "Parent" : "19"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74.mac_muladd_9s_9ns_8ns_18_4_1_U65", "Parent" : "19"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74.mac_muladd_8s_8s_17s_17_4_1_U66", "Parent" : "19"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74.mac_muladd_9ns_8s_18s_18_4_1_U67", "Parent" : "19"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.grp_yuv2rgb_Pipeline_YUV2RGB_LOOP_X_YUV2RGB_LOOP_Y_fu_74.flow_control_loop_pipe_sequential_init_U", "Parent" : "19"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.yuv2rgb_U0.mul_16ns_16ns_32_1_1_U80", "Parent" : "18"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Y_scale_c_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.U_scale_c_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.V_scale_c_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_yuv_channels_ch1_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_yuv_channels_ch2_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_yuv_channels_ch3_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_yuv_width_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_yuv_height_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_scale_channels_ch1_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_scale_channels_ch2_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_scale_channels_ch3_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_scale_width_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_scale_height_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_yuv_scale_U0_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_yuv2rgb_U0_U", "Parent" : "0"}]}
