// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dct_Loop_Col_DCT_Loop_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        col_inbuf_i_0_address0,
        col_inbuf_i_0_ce0,
        col_inbuf_i_0_q0,
        col_inbuf_i_1_address0,
        col_inbuf_i_1_ce0,
        col_inbuf_i_1_q0,
        col_inbuf_i_2_address0,
        col_inbuf_i_2_ce0,
        col_inbuf_i_2_q0,
        col_inbuf_i_3_address0,
        col_inbuf_i_3_ce0,
        col_inbuf_i_3_q0,
        col_inbuf_i_4_address0,
        col_inbuf_i_4_ce0,
        col_inbuf_i_4_q0,
        col_inbuf_i_5_address0,
        col_inbuf_i_5_ce0,
        col_inbuf_i_5_q0,
        col_inbuf_i_6_address0,
        col_inbuf_i_6_ce0,
        col_inbuf_i_6_q0,
        col_inbuf_i_7_address0,
        col_inbuf_i_7_ce0,
        col_inbuf_i_7_q0,
        col_outbuf_i_6_address0,
        col_outbuf_i_6_ce0,
        col_outbuf_i_6_we0,
        col_outbuf_i_6_d0,
        col_outbuf_i_5_address0,
        col_outbuf_i_5_ce0,
        col_outbuf_i_5_we0,
        col_outbuf_i_5_d0,
        col_outbuf_i_4_address0,
        col_outbuf_i_4_ce0,
        col_outbuf_i_4_we0,
        col_outbuf_i_4_d0,
        col_outbuf_i_3_address0,
        col_outbuf_i_3_ce0,
        col_outbuf_i_3_we0,
        col_outbuf_i_3_d0,
        col_outbuf_i_2_address0,
        col_outbuf_i_2_ce0,
        col_outbuf_i_2_we0,
        col_outbuf_i_2_d0,
        col_outbuf_i_1_address0,
        col_outbuf_i_1_ce0,
        col_outbuf_i_1_we0,
        col_outbuf_i_1_d0,
        col_outbuf_i_0_address0,
        col_outbuf_i_0_ce0,
        col_outbuf_i_0_we0,
        col_outbuf_i_0_d0,
        col_outbuf_i_7_address0,
        col_outbuf_i_7_ce0,
        col_outbuf_i_7_we0,
        col_outbuf_i_7_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [2:0] col_inbuf_i_0_address0;
output   col_inbuf_i_0_ce0;
input  [15:0] col_inbuf_i_0_q0;
output  [2:0] col_inbuf_i_1_address0;
output   col_inbuf_i_1_ce0;
input  [15:0] col_inbuf_i_1_q0;
output  [2:0] col_inbuf_i_2_address0;
output   col_inbuf_i_2_ce0;
input  [15:0] col_inbuf_i_2_q0;
output  [2:0] col_inbuf_i_3_address0;
output   col_inbuf_i_3_ce0;
input  [15:0] col_inbuf_i_3_q0;
output  [2:0] col_inbuf_i_4_address0;
output   col_inbuf_i_4_ce0;
input  [15:0] col_inbuf_i_4_q0;
output  [2:0] col_inbuf_i_5_address0;
output   col_inbuf_i_5_ce0;
input  [15:0] col_inbuf_i_5_q0;
output  [2:0] col_inbuf_i_6_address0;
output   col_inbuf_i_6_ce0;
input  [15:0] col_inbuf_i_6_q0;
output  [2:0] col_inbuf_i_7_address0;
output   col_inbuf_i_7_ce0;
input  [15:0] col_inbuf_i_7_q0;
output  [2:0] col_outbuf_i_6_address0;
output   col_outbuf_i_6_ce0;
output   col_outbuf_i_6_we0;
output  [15:0] col_outbuf_i_6_d0;
output  [2:0] col_outbuf_i_5_address0;
output   col_outbuf_i_5_ce0;
output   col_outbuf_i_5_we0;
output  [15:0] col_outbuf_i_5_d0;
output  [2:0] col_outbuf_i_4_address0;
output   col_outbuf_i_4_ce0;
output   col_outbuf_i_4_we0;
output  [15:0] col_outbuf_i_4_d0;
output  [2:0] col_outbuf_i_3_address0;
output   col_outbuf_i_3_ce0;
output   col_outbuf_i_3_we0;
output  [15:0] col_outbuf_i_3_d0;
output  [2:0] col_outbuf_i_2_address0;
output   col_outbuf_i_2_ce0;
output   col_outbuf_i_2_we0;
output  [15:0] col_outbuf_i_2_d0;
output  [2:0] col_outbuf_i_1_address0;
output   col_outbuf_i_1_ce0;
output   col_outbuf_i_1_we0;
output  [15:0] col_outbuf_i_1_d0;
output  [2:0] col_outbuf_i_0_address0;
output   col_outbuf_i_0_ce0;
output   col_outbuf_i_0_we0;
output  [15:0] col_outbuf_i_0_d0;
output  [2:0] col_outbuf_i_7_address0;
output   col_outbuf_i_7_ce0;
output   col_outbuf_i_7_we0;
output  [15:0] col_outbuf_i_7_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg col_outbuf_i_6_ce0;
reg col_outbuf_i_6_we0;
reg col_outbuf_i_5_ce0;
reg col_outbuf_i_5_we0;
reg col_outbuf_i_4_ce0;
reg col_outbuf_i_4_we0;
reg col_outbuf_i_3_ce0;
reg col_outbuf_i_3_we0;
reg col_outbuf_i_2_ce0;
reg col_outbuf_i_2_we0;
reg col_outbuf_i_1_ce0;
reg col_outbuf_i_1_we0;
reg col_outbuf_i_0_ce0;
reg col_outbuf_i_0_we0;
reg col_outbuf_i_7_ce0;
reg col_outbuf_i_7_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] add_ln81_fu_249_p2;
reg   [3:0] add_ln81_reg_302;
wire    ap_CS_fsm_state2;
wire   [2:0] trunc_ln81_fu_267_p1;
reg   [2:0] trunc_ln81_reg_307;
reg   [15:0] col_inbuf_i_0_load_reg_352;
wire    ap_CS_fsm_state3;
reg   [15:0] col_inbuf_i_1_load_reg_357;
reg   [15:0] col_inbuf_i_2_load_reg_362;
reg   [15:0] col_inbuf_i_3_load_reg_367;
reg   [15:0] col_inbuf_i_4_load_reg_372;
reg   [15:0] col_inbuf_i_5_load_reg_377;
reg   [15:0] col_inbuf_i_6_load_reg_382;
reg   [15:0] col_inbuf_i_7_load_reg_387;
wire    grp_dct_1d_fu_190_ap_start;
wire    grp_dct_1d_fu_190_ap_done;
wire    grp_dct_1d_fu_190_ap_idle;
wire    grp_dct_1d_fu_190_ap_ready;
wire   [2:0] grp_dct_1d_fu_190_dst_address0;
wire    grp_dct_1d_fu_190_dst_ce0;
wire    grp_dct_1d_fu_190_dst_we0;
wire   [15:0] grp_dct_1d_fu_190_dst_d0;
reg    grp_dct_1d_fu_190_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln81_fu_255_p1;
wire   [0:0] icmp_ln81_fu_243_p2;
reg   [3:0] i_fu_82;
reg    ap_block_state4_on_subcall_done;
reg    ap_block_state1;
reg    col_inbuf_i_0_ce0_local;
reg    col_inbuf_i_1_ce0_local;
reg    col_inbuf_i_2_ce0_local;
reg    col_inbuf_i_3_ce0_local;
reg    col_inbuf_i_4_ce0_local;
reg    col_inbuf_i_5_ce0_local;
reg    col_inbuf_i_6_ce0_local;
reg    col_inbuf_i_7_ce0_local;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_dct_1d_fu_190_ap_start_reg = 1'b0;
#0 i_fu_82 = 4'd0;
end

dct_dct_1d grp_dct_1d_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_1d_fu_190_ap_start),
    .ap_done(grp_dct_1d_fu_190_ap_done),
    .ap_idle(grp_dct_1d_fu_190_ap_idle),
    .ap_ready(grp_dct_1d_fu_190_ap_ready),
    .src_0_val(col_inbuf_i_0_load_reg_352),
    .src_1_val(col_inbuf_i_1_load_reg_357),
    .src_2_val(col_inbuf_i_2_load_reg_362),
    .src_3_val(col_inbuf_i_3_load_reg_367),
    .src_4_val(col_inbuf_i_4_load_reg_372),
    .src_5_val(col_inbuf_i_5_load_reg_377),
    .src_6_val(col_inbuf_i_6_load_reg_382),
    .src_7_val(col_inbuf_i_7_load_reg_387),
    .dst_address0(grp_dct_1d_fu_190_dst_address0),
    .dst_ce0(grp_dct_1d_fu_190_dst_ce0),
    .dst_we0(grp_dct_1d_fu_190_dst_we0),
    .dst_d0(grp_dct_1d_fu_190_dst_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln81_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_1d_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd7)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd1)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd2)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd3)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd4)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd5)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln81_reg_307 == 3'd6)))) begin
            grp_dct_1d_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_dct_1d_fu_190_ap_ready == 1'b1)) begin
            grp_dct_1d_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_82 <= 4'd0;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_82 <= add_ln81_reg_302;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln81_reg_302 <= add_ln81_fu_249_p2;
        trunc_ln81_reg_307 <= trunc_ln81_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        col_inbuf_i_0_load_reg_352 <= col_inbuf_i_0_q0;
        col_inbuf_i_1_load_reg_357 <= col_inbuf_i_1_q0;
        col_inbuf_i_2_load_reg_362 <= col_inbuf_i_2_q0;
        col_inbuf_i_3_load_reg_367 <= col_inbuf_i_3_q0;
        col_inbuf_i_4_load_reg_372 <= col_inbuf_i_4_q0;
        col_inbuf_i_5_load_reg_377 <= col_inbuf_i_5_q0;
        col_inbuf_i_6_load_reg_382 <= col_inbuf_i_6_q0;
        col_inbuf_i_7_load_reg_387 <= col_inbuf_i_7_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_0_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_1_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_2_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_3_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_4_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_5_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_6_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        col_inbuf_i_7_ce0_local = 1'b1;
    end else begin
        col_inbuf_i_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd0))) begin
        col_outbuf_i_0_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd0))) begin
        col_outbuf_i_0_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd1))) begin
        col_outbuf_i_1_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd1))) begin
        col_outbuf_i_1_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd2))) begin
        col_outbuf_i_2_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd2))) begin
        col_outbuf_i_2_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd3))) begin
        col_outbuf_i_3_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd3))) begin
        col_outbuf_i_3_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd4))) begin
        col_outbuf_i_4_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd4))) begin
        col_outbuf_i_4_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd5))) begin
        col_outbuf_i_5_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd5))) begin
        col_outbuf_i_5_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd6))) begin
        col_outbuf_i_6_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd6))) begin
        col_outbuf_i_6_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd7))) begin
        col_outbuf_i_7_ce0 = grp_dct_1d_fu_190_dst_ce0;
    end else begin
        col_outbuf_i_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln81_reg_307 == 3'd7))) begin
        col_outbuf_i_7_we0 = grp_dct_1d_fu_190_dst_we0;
    end else begin
        col_outbuf_i_7_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln81_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln81_fu_249_p2 = (i_fu_82 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = (((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd7)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd0)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd1)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd2)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd3)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd4)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd5)) | ((grp_dct_1d_fu_190_ap_done == 1'b0) & (trunc_ln81_reg_307 == 3'd6)));
end

assign col_inbuf_i_0_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_0_ce0 = col_inbuf_i_0_ce0_local;

assign col_inbuf_i_1_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_1_ce0 = col_inbuf_i_1_ce0_local;

assign col_inbuf_i_2_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_2_ce0 = col_inbuf_i_2_ce0_local;

assign col_inbuf_i_3_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_3_ce0 = col_inbuf_i_3_ce0_local;

assign col_inbuf_i_4_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_4_ce0 = col_inbuf_i_4_ce0_local;

assign col_inbuf_i_5_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_5_ce0 = col_inbuf_i_5_ce0_local;

assign col_inbuf_i_6_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_6_ce0 = col_inbuf_i_6_ce0_local;

assign col_inbuf_i_7_address0 = zext_ln81_fu_255_p1;

assign col_inbuf_i_7_ce0 = col_inbuf_i_7_ce0_local;

assign col_outbuf_i_0_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_0_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_1_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_1_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_2_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_2_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_3_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_3_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_4_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_4_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_5_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_5_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_6_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_6_d0 = grp_dct_1d_fu_190_dst_d0;

assign col_outbuf_i_7_address0 = grp_dct_1d_fu_190_dst_address0;

assign col_outbuf_i_7_d0 = grp_dct_1d_fu_190_dst_d0;

assign grp_dct_1d_fu_190_ap_start = grp_dct_1d_fu_190_ap_start_reg;

assign icmp_ln81_fu_243_p2 = ((i_fu_82 == 4'd8) ? 1'b1 : 1'b0);

assign trunc_ln81_fu_267_p1 = i_fu_82[2:0];

assign zext_ln81_fu_255_p1 = i_fu_82;

endmodule //dct_Loop_Col_DCT_Loop_proc
